// Generated by tools/star-manifest/gen_cs.py; do not edit.
using System;
using System.Collections.Generic;

namespace SodRpg.Core.Game
{
    public static partial class StarClusters
    {
        private static readonly object GeneratedLock = new object();
        private static bool generatedRegistered;

        /// <summary>Heroes whose complete star map was generated from the manifest (never a partial hero).</summary>
        public static readonly IReadOnlyList<string> GeneratedHeroes = Array.AsReadOnly(new string[0]);

        /// <summary>Install one generated hero's authored tree, then its migration rules (tests and tools; production uses RegisterAllGenerated).</summary>
        public static void RegisterGeneratedHero(string heroKey)
        {
            switch (heroKey)
            {
                default: throw new ArgumentException("No generated star map for " + heroKey);
            }
        }

        /// <summary>Install every generated hero's authored tree and its migration rules. Idempotent and thread-safe.</summary>
        public static void RegisterAllGenerated()
        {
            lock (GeneratedLock)
            {
                if (generatedRegistered) return;
                foreach (string hero in GeneratedHeroes) RegisterGeneratedHero(hero);
                generatedRegistered = true;
            }
        }
    }
}
