using System;

namespace SodRpg.Core.Game
{
    public static partial class BossProfiles
    {
        public const string SeekerSetId = "set.boss_seeker";
        public const string SeekerRewardId = "boss_seeker.soul_prison";
        public const string SeekerNativeContract = "exact-DeathInterrupt-callback-and-quality-native-heal;final-native-heal-plus-min10percent-.20H;one-native-dispatch;preserve-discarded-native-infinite-shield-HP1-consumption-invulnerability;overflow-self25percent-cap.30H-6s-ally25percent-cap.40H-3s-nearest-alive-allied-hero6m-excluding-self;confirmed-native-consumption-retains-finite-shields;manual-reduction-death-room-clears;actor-parent-gem-skill-pool-life-room-run-gear-guards";
        public const string SeekerEventOrder = "E1-advance-green-purple-red-once-even-during-CD;phase-shot-CD3;existing-stage3-double-copies-current-phase-once-then-disappears;parts;E3-departure-only-shared-single-nonEntity-double;E2-fixed-claw-fan-three-pulses-and-once-shield";
        private static BossChannelDef SeekerChannel(string id,int value,int cap,BossCoefficientKind kind=BossCoefficientKind.Damage) => new BossChannelDef(id,value*1000,cap*1000,kind);
        private static BossMoveProfile SeekerProfile(string id,string ja,string en,BossChannelDef[] channels,params BossAction[] actions) => new BossMoveProfile("boss_seeker."+id,SeekerSetId,new Txt(ja,en),channels,actions);
        private static BossAction SeekerOrb(BossEvent kind,string channel,int cd,int life=1000,int speed=8000) => new BossAction(kind,BossMechanism.Projectile,BossPayload.Damage,channel,BossShape.Circle,BossAnchor.Hit,cooldownMillis:cd,lifetimeMillis:life,maxInstances:1,radiusMilli:1500,rangeMilli:8000,widthMilli:400,speedMilli:speed,firstHitOnly:true);
        internal static BossMoveProfile[] CreateSeekerMoves() => new[]
        {
            SeekerProfile("weapon","主撃で主対象の確定点へ球1発。射程8m・寿命1秒、到達時半径1.5mへ18%H（上限54）、CD3秒。壁爆発なし。","A native main hit fires one orb at the fixed main-target point: range8m, lifetime1s, terminal1.5m explosion18%H(cap54), CD3s; no wall explosion.",new[]{SeekerChannel("SeekerOrb",18,54)},SeekerOrb(BossEvent.MainHit,"SeekerOrb",3000)),
            SeekerProfile("armor","native被弾で本人地点に非Entity分身1体/2秒、本人shield18%H（上限54）/2秒、CD10秒。3点分身と合算最大1、taunt/標的変更なし。","Native damage taken displays one non-Entity double at your position for2s and grants18%H self shield(cap54)/2s, CD10s. Shared max1 with3-piece double; no taunt or target changes.",new[]{SeekerChannel("SeekerDoubleGuard",18,54,BossCoefficientKind.Shield)},new BossAction(BossEvent.NativeDamageTaken,BossMechanism.Defense,BossPayload.Shield,"SeekerDoubleGuard",cooldownMillis:10000,lifetimeMillis:2000,maxInstances:1)),
            SeekerProfile("charm","記憶使用確定で8m内最寄り敵へ誘導球1発。寿命2秒・移動上限8m、命中または満了で半径1.5mへ24%H（上限72）を1回、CD6秒。","Confirmed normal/ultimate memory use fires one homing orb at the nearest enemy within8m:2s lifetime,8m travel cap, one1.5m explosion24%H(cap72) on hit or expiration, CD6s.",new[]{SeekerChannel("SeekerChaser",24,72)},SeekerOrb(BossEvent.MemoryUse,"SeekerChaser",6000,2000,4000)),
            SeekerProfile("head","主撃で主対象点8m以内を0.4秒予告、半径2mへ20%H（上限60）、CD5秒。画面暗転なし。","A native main hit warns the fixed main-target point within8m for0.4s, then20%H(cap60) in2m, CD5s; no screen darkening.",new[]{SeekerChannel("SeekerAim",20,60)},new BossAction(BossEvent.MainHit,BossMechanism.Field,BossPayload.Damage,"SeekerAim",BossShape.Circle,BossAnchor.Hit,cooldownMillis:5000,delayMillis:400,maxInstances:1,radiusMilli:2000,rangeMilli:8000)),
            SeekerProfile("hands","記憶使用確定で8m内最寄り敵の確定点へ半径2m/2秒の紫場1個。0.5/1.5秒に各10%H（上限30）、CD6秒。追従/子場なし。","Confirmed memory use fixes the nearest enemy point within8m: one2m purple field for2s,10%H(cap30) at0.5/1.5s, CD6s. No following or child fields.",new[]{SeekerChannel("SeekerPurple",10,30)},new BossAction(BossEvent.MemoryUse,BossMechanism.Field,BossPayload.Damage,"SeekerPurple",BossShape.Circle,BossAnchor.Hit,cooldownMillis:6000,delayMillis:500,lifetimeMillis:2000,intervalMillis:1000,count:2,maxInstances:1,radiusMilli:2000,rangeMilli:8000)),
            SeekerProfile("feet","本人native移動完了で出発点を0.3秒予告、半径1.5mへ22%H（上限66）Fire＋非boss/非CC免疫にstun0.25秒、CD5秒。生成移動除外。","Native owner movement completion warns the departure point for0.3s, then22%H Fire(cap66) in1.5m and0.25s stun only to non-boss, non-CC-immune enemies, CD5s; generated movement excluded.",new[]{SeekerChannel("SeekerFissure",22,66)},new BossAction(BossEvent.MovementCompleted,BossMechanism.Field,BossPayload.Damage,"SeekerFissure",cooldownMillis:5000,delayMillis:300,maxInstances:1,radiusMilli:1500,magnitudeMilli:250,element:BossElement.Fire)),
            SeekerProfile("stage2","主撃成功ごと緑→紫→赤へ1段進行（1activation1回）。CD3秒で相攻撃16%H：緑8m/1秒球、紫主対象点0.4秒予告/半径1.5m、赤同点半径1.5m Fire。","Each successful native main activation advances green→purple→red once, even during CD. Phase attack16%H, CD3s: green8m/1s orb; purple fixed-target0.4s warning/1.5m; red same1.5m point with Fire.",new[]{SeekerChannel("SeekerPhase",16,16)},SeekerOrb(BossEvent.MainHit,"SeekerPhase",3000),new BossAction(BossEvent.Clock,BossMechanism.Field,BossPayload.Damage,"SeekerPhase",BossShape.Circle,BossAnchor.Hit,delayMillis:400,maxInstances:1,radiusMilli:1500,rangeMilli:8000),new BossAction(BossEvent.Clock,BossMechanism.ShapeAttack,BossPayload.Damage,"SeekerPhase",BossShape.Circle,BossAnchor.Hit,maxInstances:1,radiusMilli:1500,rangeMilli:8000,element:BossElement.Fire)),
            SeekerProfile("stage3","本人native移動完了で出発点に非Entity分身1体/3秒、CD5秒。次主撃の相を分身起点から主対象確定点へ12%H/射程8mで1回複製し即消失。Armorと合算最大1、召喚proc/lootなし。","Native movement completion leaves one non-Entity double at departure for3s, CD5s. The next main hit copies its phase once from the double to the fixed target for12%H/range8m, then vanishes. Shared max1 with Armor; no summon proc/loot.",new[]{SeekerChannel("SeekerEcho",12,12)},new BossAction(BossEvent.MovementCompleted,BossMechanism.Deployable,BossPayload.Deploy,"SeekerEcho",cooldownMillis:5000,lifetimeMillis:3000,maxInstances:1,rangeMilli:8000)),
            SeekerProfile("stage6","記憶使用確定で8m内敵点を固定照準。0.5/0.75/1秒後、長4m/90度の爪扇各30%H（計90/上限100）＋本人shield38%H（上限40）/2.5秒を1回、CD10秒。操作block/無敵/暗転なし。","Confirmed memory use fixes an enemy point within8m; at0.5/0.75/1s three4m/90-degree claw fans each deal30%H(total90/cap100), plus one38%H self shield(cap40)/2.5s, CD10s. No control block, invulnerability or darkening.",new[]{SeekerChannel("SeekerClaws",90,100),SeekerChannel("SeekerClawGuard",38,40,BossCoefficientKind.Shield)},new BossAction(BossEvent.MemoryUse,BossMechanism.Field,BossPayload.Damage,"SeekerClaws",BossShape.Fan,BossAnchor.Hit,cooldownMillis:10000,delayMillis:500,intervalMillis:250,count:3,maxInstances:1,rangeMilli:4000,angleMilli:90000,magnitudeMilli:8000),new BossAction(BossEvent.Clock,BossMechanism.Defense,BossPayload.Shield,"SeekerClawGuard",lifetimeMillis:2500,maxInstances:1))
        };
        internal static BossRewardProfile[] CreateSeekerRewards()
        {
            BossRewardAction Heal()=>new BossRewardAction(BossRewardActionKind.NativeHeal,10000,10000,magnitudeMilli:20000);
            BossRewardAction Self()=>new BossRewardAction(BossRewardActionKind.NativeShield,25000,25000,durationMillis:6000,order:1,targetCapMilli:30000);
            return new[]{new BossRewardProfile(SeekerRewardId,SeekerSetId,"Gem_U_SoulPrison",BossRewardAdapter.SoulPrison,new[]{
                new BossRewardStage(1,new Txt("当該native救命のquality倍率済み最終Healへmin(元回復×10%,0.20H)加算。別Healなし、HP=1/元overflow/消費/無敵不変。","Only the native rescue's final quality-scaled heal gains min(original10%,0.20H). No second heal; preserve HP1, native overflow, consumption and invulnerability."),new[]{Heal()}),
                new BossRewardStage(2,new Txt("段階1＋同救命Healのoverflow25%を本人追加shield（上限0.30H）/6秒へ1回。元同量無期限shieldは不変。","Stage1 plus once grant an extra self shield of25% rescue overflow(cap0.30H)/6s; preserve native full-overflow infinite shield."),new[]{Heal(),Self()}),
                new BossRewardStage(3,new Txt("段階2＋同overflow25%を本人6m内最寄りalive味方Hero1人（本人除外）へshield（上限0.40H）/3秒を1回。消費確定後有限shieldは寿命まで保持、任意減装/死亡/部屋で解除。無敵延長なし。","Stage2 plus once shield nearest alive allied Hero within6m, excluding self, for25% rescue overflow(cap0.40H)/3s. Confirmed consumption preserves finite shields until expiry; voluntary gear removal, death or room change clears them. No invulnerability extension."),new[]{Heal(),Self(),new BossRewardAction(BossRewardActionKind.NativeShield,25000,25000,durationMillis:3000,rangeMilli:6000,order:2,targetCapMilli:40000)})})};
        }
        public static UniqueDef[] CreateSeekerPieces()=>new[]{
            new UniqueDef("unique.boss_seeker.weapon","weapon.dream_wand",new Txt("幻彩の球杖","Mirage Orb Rod"),SeekerSetId,"boss_seeker.weapon"),
            new UniqueDef("unique.boss_seeker.armor","armor.mirrorsilk_robe",new Txt("分身の外套","Double Mantle"),SeekerSetId,"boss_seeker.armor"),
            new UniqueDef("unique.boss_seeker.charm","charm.pulsing_core",new Txt("魂窓の珠","Soulwindow Pearl"),SeekerSetId,"boss_seeker.charm"),
            new UniqueDef("unique.boss_seeker.head","head.moth_wing_mask",new Txt("狭界の面","Narrowworld Mask"),SeekerSetId,"boss_seeker.head"),
            new UniqueDef("unique.boss_seeker.hands","hands.shadow_gloves",new Txt("紫影の手袋","Violetshadow Gloves"),SeekerSetId,"boss_seeker.hands"),
            new UniqueDef("unique.boss_seeker.feet","feet.ember_treads",new Txt("裂け目の歩み","Fissure Steps"),SeekerSetId,"boss_seeker.feet")};
        public static SetDef[] CreateSeekerSets()=>new[]{new SetDef{Id=SeekerSetId,Name=new Txt("幻彩の追装","Mirage Spectrum Gear"),BossTypeName="Mon_DarkCave_BossSeeker",TwoPiece=Array.Empty<StatLine>(),ThreePiece=Array.Empty<PowerLine>(),SixPiece=Array.Empty<PowerLine>(),BossStages=new[]{new BossSetStage(2,"boss_seeker.stage2"),new BossSetStage(3,"boss_seeker.stage3"),new BossSetStage(6,"boss_seeker.stage6")},BossReward=SeekerRewardId,LinkStages=new[]{new SetLinkStage(2,new LinkDef{Kind=LinkKind.BossReward,Value=1,Requires=new[]{"Gem_U_SoulPrison"}}),new SetLinkStage(4,new LinkDef{Kind=LinkKind.BossReward,Value=2,Requires=new[]{"Gem_U_SoulPrison"}}),new SetLinkStage(6,new LinkDef{Kind=LinkKind.BossReward,Value=3,Requires=new[]{"Gem_U_SoulPrison"}})}}};
    }
}
