using System;

namespace SodRpg.Core.Game
{
    public static partial class BossProfiles
    {
        public const string ErebosSetId = "set.boss_erebos";
        public const string ErebosRewardId = "boss_erebos.last_starlight";
        public const string ErebosEventOrder = "expire-and-reconcile-total2-oldest-replaced-tokens;one-native-input;pending-E3-once-push-to-pull;consume-old-marker-before-parts;capture-consume-boundary3-before-E2-parts;E2-stage2-marker;equipped-parts;stage6-reservation-last-survives-same-input-oldest-replacement;stage6-fixed-center-orthogonal-centered-lines-telegraph-at2-hit2.5-ripple3;prepare-E3-angle-once;native-prepare-relocate-once-from-original-center";
        public const string ErebosNativeContract = "exact-OnCreateSequenced-prehook-gem-skill-owner-room-run-unique-lives;cached-gem-survives-castcomplete-parent-rebind;original-iterator-two-native-waits-adapted-to-live-deadline-predicates;independent-delay-radius-duration-own-deltas;prepare-delay-minus-min0.2-max0-native-minus0.25;attract-plus-min1-max0-12-minus-base;tick-plus-min0.5-max0-8-minus-base;duration-plus-min1-max0-6-minus-base;restore-wait-deadline-not-just-fields;prepare-once-valid-E3-original-center-to-end-max2m-Network_info-position-FX-sync;active-fixed;native-invalid-gem-skill-selfdestroy-unchanged;host-only-no-generated-origin;pool-disable-own-delta-restore";
        private static BossMoveProfile ErebosProfile(string suffix, string ja, string en, BossChannelDef[] channels, params BossAction[] actions)
            => new BossMoveProfile("boss_erebos." + suffix, ErebosSetId, new Txt(ja, en), channels, actions);
        private static BossAction ErebosCircle(BossEvent trigger, string channel, int radius, int delay = 0, int cooldown = 0, int lifetime = 0)
            => new BossAction(trigger, BossMechanism.ShapeAttack, BossPayload.Damage, channel, cooldownMillis:cooldown, delayMillis:delay,
                lifetimeMillis:lifetime, maxInstances:2, radiusMilli:radius, element:BossElement.Light, replaceOldest:true);
        internal static BossMoveProfile[] CreateErebosMoves() => new[]
        {
            ErebosProfile("weapon", "通常攻撃命中時、命中した敵の方向へ長さ6m・幅0.6mの直線を0.3秒間予告し、0.3秒間隔で2回、光属性ダメージ（各攻撃力・魔力の高い方の8%、敵1体につき最大2回命中）を与える。再使用まで5秒。", "When your basic attack hits, show a warning for 0.3 seconds along a line toward the enemy, 6m long and 0.6m wide. Then deal Light damage twice, 0.3 seconds apart, each equal to 8% of whichever is higher: your Attack or Ability Power. Each enemy can be hit up to twice. Cooldown: 5 seconds.",
                new[] { C("ErebosGaze",8,8) }, new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"ErebosGaze",BossShape.Line,cooldownMillis:5000,delayMillis:300,intervalMillis:300,count:2,maxInstances:2,rangeMilli:6000,widthMilli:600,element:BossElement.Light,replaceOldest:true)),
            ErebosProfile("armor", "被ダメージ時、その地点を0.5秒間予告し、半径2mの範囲に光属性ダメージ（攻撃力・魔力の高い方の12%）を与えて0.2秒かけて外側へ最大0.5m押し出す（ボスと行動妨害が効かない敵は移動しない）。再使用まで8秒。", "When you take damage, mark that location with a warning for 0.5 seconds. Deal Light damage in a 2m radius equal to 12% of whichever is higher: your Attack or Ability Power, and push enemies outward up to 0.5m over 0.2 seconds. Bosses and enemies immune to crowd control are not moved. Cooldown: 8 seconds.",
                new[] { C("ErebosLanding",12,12) }, ErebosCircle(BossEvent.NativeDamageTaken,"ErebosLanding",2000,500,8000)),
            ErebosProfile("charm", "自身の移動スキル完了時、着地地点を0.3秒間予告し、半径2.5mの範囲に光属性ダメージ（攻撃力・魔力の高い方の10%）を与え、最大3体の敵を0.3秒かけて外側へ最大0.6m押し出す（ボスと行動妨害が効かない敵は移動しない）。再使用まで6秒。", "When your movement skill ends, mark your landing location with a warning for 0.3 seconds. Deal Light damage in a 2.5m radius equal to 10% of whichever is higher: your Attack or Ability Power, and push up to 3 enemies outward up to 0.6m over 0.3 seconds. Bosses and enemies immune to crowd control are not moved. Cooldown: 6 seconds.",
                new[] { C("ErebosWhitehole",10,10) }, ErebosCircle(BossEvent.MovementCompleted,"ErebosWhitehole",2500,300,6000)),
            ErebosProfile("head", "記憶を使ったとき、照準地点（自身から8m以内）の半径1.8mを0.7秒間予告し、火属性ダメージ（攻撃力・魔力の高い方の18%）を着弾させる（HP割合ダメージやノックアップ/スタン効果はない）。再使用まで7秒。", "When you use a memory, show a warning in a 1.8m radius at your aim location within 8m of you for 0.7 seconds, then deal Fire damage equal to 18% of whichever is higher: your Attack or Ability Power. This deals no percentage-of-HP damage and does not knock up or stun. Cooldown: 7 seconds.",
                new[] { C("ErebosMeteor",18,18) }, new BossAction(BossEvent.MemoryUse,BossMechanism.ShapeAttack,BossPayload.Damage,"ErebosMeteor",anchor:BossAnchor.Cursor,cooldownMillis:7000,delayMillis:700,maxInstances:2,radiusMilli:1800,rangeMilli:8000,element:BossElement.Fire,replaceOldest:true)),
            ErebosProfile("hands", "通常攻撃命中時、命中した敵の位置（自身から8m以内）へ0.2秒差で2発の弾を射出する（弾速12m/秒、持続1秒）。着弾地点に半径1mの予告後、光属性ダメージ（各攻撃力・魔力の高い方の8%、敵1体につき最大2回命中）を与える（弾の飛行中ダメージや壁衝突時の爆発はない）。再使用まで6秒。", "When your basic attack hits, fire 2 projectiles toward the enemy's location within 8m of you, 0.2 seconds apart. They travel at 12m/s and last 1 second. After a warning in a 1m radius at the impact location, each deals Light damage equal to 8% of whichever is higher: your Attack or Ability Power. Each enemy can be hit up to twice. Projectiles deal no damage in flight and do not explode when they hit a wall. Cooldown: 6 seconds.",
                new[] { C("ErebosStarRain",8,8) }, new BossAction(BossEvent.MainHit,BossMechanism.Projectile,BossPayload.Damage,"ErebosStarRain",anchor:BossAnchor.Hit,cooldownMillis:6000,lifetimeMillis:1000,intervalMillis:200,count:2,maxInstances:2,radiusMilli:1000,rangeMilli:8000,widthMilli:200,speedMilli:12000,element:BossElement.Light,replaceOldest:true)),
            ErebosProfile("feet", "自身の移動スキル完了時、着地地点から0.2秒／0.4秒／0.6秒後にそれぞれ半径1m／2m／3mの光の波紋を広げ、光属性ダメージ（それぞれ攻撃力・魔力の高い方の4%／5%／6%、敵1体につき最大3回命中）を与える。再使用まで6秒。", "When your movement skill ends, spread Light ripples from your landing location after 0.2, 0.4, and 0.6 seconds, with radii of 1m, 2m, and 3m respectively. They deal Light damage equal to 4%, 5%, and 6% of whichever is higher: your Attack or Ability Power, respectively. Each enemy can be hit up to 3 times. Cooldown: 6 seconds.",
                new[] { C("ErebosRippleFirst",4,4),C("ErebosRippleSecond",5,5),C("ErebosRippleThird",6,6) }, ErebosCircle(BossEvent.MovementCompleted,"ErebosRippleFirst",1000,200,6000), ErebosCircle(BossEvent.Clock,"ErebosRippleSecond",2000,400), ErebosCircle(BossEvent.Clock,"ErebosRippleThird",3000,600)),
            ErebosProfile("stage2", "記憶を使ったとき、照準地点（8m以内）に4秒間持続する中心の印を設置する（未消費の印は同時に1個のみ存在でき、再設置時は古い印を置換。設置物はエレビオス効果全体で最大2個まで）。次の通常攻撃が敵に命中したときに印を消費し、半径2mに攻撃力・魔力の高い方の10%、その0.3秒後に半径3mに光属性ダメージ（攻撃力・魔力の高い方の14%）の波紋を発生させる。再使用まで6秒。", "When you use a memory, place a center mark at your aim location within 8m for 4 seconds. Only one unconsumed mark can exist; placing another replaces it. Up to 2 placed effects can exist across all Erebos effects. When your next basic attack hits an enemy, consume the mark to create a ripple in a 2m radius dealing 10% of whichever is higher: your Attack or Ability Power, then a Light ripple in a 3m radius after 0.3 seconds dealing 14%. Cooldown: 6 seconds.",
                new[] { C("ErebosRippleStart",10,10),C("ErebosRippleEnd",14,14) }, new BossAction(BossEvent.MemoryUse,BossMechanism.Field,BossPayload.Mark,lifetimeMillis:4000,maxInstances:1,radiusMilli:3000,rangeMilli:8000,replaceOldest:true,element:BossElement.Light), ErebosCircle(BossEvent.MainHit,"ErebosRippleStart",2000,0,6000), ErebosCircle(BossEvent.Clock,"ErebosRippleEnd",3000,300)),
            ErebosProfile("stage3", "印の待機中に自身の移動スキルを完了すると、効果が「押し出し」から「引き寄せ」へと変化する（印1個につき1回のみ、押し出しには戻らない）。波紋発生の直前、半径3m以内の敵最大3体を0.3秒かけて外側（変化時は内側）へ最大0.8m移動させる（ボスと行動妨害が効かない敵は移動しない）。印を消費すると境界の印を1つ獲得する（持続12秒、最大3個まで蓄積）。", "Completing your movement skill while a mark is waiting changes its push into a pull. This can happen only once per mark and cannot be reversed. Just before the ripple appears, move up to 3 enemies within 3m outward, or inward after the change, up to 0.8m over 0.3 seconds. Bosses and enemies immune to crowd control are not moved. Consuming the mark grants one boundary mark, lasting 12 seconds and stacking up to 3 times.",
                new[] { C("ErebosPolarity",80,80,BossCoefficientKind.Distance) }, new BossAction(BossEvent.MovementCompleted,BossMechanism.Ledger,BossPayload.Mode,count:1,maxInstances:1,lifetimeMillis:4000,radiusMilli:3000,magnitudeMilli:800,element:BossElement.Light), new BossAction(BossEvent.MainHit,BossMechanism.Ledger,BossPayload.Mark,count:3,maxInstances:1,lifetimeMillis:12000,element:BossElement.Light)),
            ErebosProfile("stage6", "境界の印を3個蓄積した状態で記憶を使ったとき、全ての印を消費して照準地点（8m以内）に3秒間、半径4mの星域を展開し、自身に3秒間、攻撃力・魔力の高い方の38%分（上限40%）の障壁を付与する。星域展開から2秒後、中心で直交する2本の直線（長さ6m、幅0.6m）を0.5秒間予告した後に各攻撃力・魔力の高い方の22.5%の光属性ダメージを与え、3秒後には中心から半径4mの円形範囲に攻撃力・魔力の高い方の45%の光属性ダメージを発生させる。直線の発動前（2.5秒以内）に移動スキルを完了すると、直線の向きを着地地点の方向へ1回のみ変更できる（移動を行わなくても発動する）。再使用まで10秒。", "When you use a memory with 3 boundary marks, consume them all to create a starfield with a 4m radius at your aim location within 8m for 3 seconds. Also gain a shield for 3 seconds equal to 38% of whichever is higher: your Attack or Ability Power (cap: 40%). After 2 seconds, show a warning for 0.5 seconds along two perpendicular lines crossing at the center, each 6m long and 0.6m wide, then deal Light damage along each equal to 22.5%. After 3 seconds, deal Light damage in a 4m radius from the center equal to 45%. Completing a movement skill before the lines fire, within 2.5 seconds, can reorient them toward your landing location once. They fire even if you do not move. Cooldown: 10 seconds.",
                new[] { C("ErebosFinale",90,100), C("ErebosFinaleShield",38,40,BossCoefficientKind.Shield) }, ErebosCircle(BossEvent.MemoryUse,"ErebosFinale",4000,3000,10000,3000), new BossAction(BossEvent.Clock,BossMechanism.ShapeAttack,BossPayload.Damage,"ErebosFinale",BossShape.Line,delayMillis:2500,maxInstances:2,count:2,rangeMilli:6000,widthMilli:600,element:BossElement.Light), new BossAction(BossEvent.MemoryUse,BossMechanism.Defense,BossPayload.Shield,"ErebosFinaleShield",lifetimeMillis:3000,maxInstances:1,element:BossElement.Light)),
        };
        internal static BossRewardProfile[] CreateErebosRewards()
        {
            BossRewardAction Delay() => new BossRewardAction(BossRewardActionKind.NativeInterval,200,200,durationMillis:250,order:0);
            BossRewardAction Attract() => new BossRewardAction(BossRewardActionKind.NativeState,1000,1000,rangeMilli:12000,order:1);
            BossRewardAction Tick() => new BossRewardAction(BossRewardActionKind.NativeState,500,500,rangeMilli:8000,order:2);
            BossRewardAction Relocate() => new BossRewardAction(BossRewardActionKind.NativeTarget,2000,2000,count:1,rangeMilli:2000,order:3);
            BossRewardAction Duration() => new BossRewardAction(BossRewardActionKind.NativeInterval,1000,1000,durationMillis:6000,order:4);
            return new[] { new BossRewardProfile(ErebosRewardId,ErebosSetId,"Gem_U_LastStarlight",BossRewardAdapter.LastStarlight,new[]
            {
                new BossRewardStage(1,new Txt("「ラストスターライト」の発動準備時間を最大0.20秒短縮する（0.25秒未満には短縮されない）。装備解除時は元の待機時間に戻る。", "Reduce Last Starlight's preparation time by up to 0.20 seconds, without reducing it below 0.25 seconds. Unequipping restores its original waiting time."),new[] { Delay() }),
                new BossRewardStage(2,new Txt("段階1の効果に加え、引き寄せ半径を最大1m（上限12mまで）、持続ダメージ半径を最大0.5m（上限8mまで）それぞれ拡大する。", "In addition to Stage 1, increase the pull radius by up to 1m, to a maximum of 12m, and the damage-over-time radius by up to 0.5m, to a maximum of 8m."),new[] { Delay(),Attract(),Tick() }),
                new BossRewardStage(3,new Txt("段階2の効果に加え、準備中に移動スキルを完了すると、効果の中心を元の位置から着地地点の方向へ最大2m再照準できる（1回のみ、発動後は位置固定）。さらに持続時間を最大1秒延長する（上限6秒まで）。", "In addition to Stage 2, completing a movement skill during preparation lets you move the effect's center up to 2m from its original position toward your landing location, once only. The center stays fixed after activation. Also extend the duration by up to 1 second, to a maximum of 6 seconds."),new[] { Delay(),Attract(),Tick(),Relocate(),Duration() }),
            }) };
        }
        public static UniqueDef[] CreateErebosPieces() => new[]
        {
            new UniqueDef("unique.boss_erebos.weapon","weapon.star_harp",new Txt("終星の波琴","Laststar Waveharp"),ErebosSetId,"boss_erebos.weapon"),
            new UniqueDef("unique.boss_erebos.armor","armor.star_mantle",new Txt("重力なき肩衣","Weightless Mantle"),ErebosSetId,"boss_erebos.armor"),
            new UniqueDef("unique.boss_erebos.charm","charm.dream_lens",new Txt("残照の星核","Afterglow Starcore"),ErebosSetId,"boss_erebos.charm"),
            new UniqueDef("unique.boss_erebos.head","head.ember_crown",new Txt("隕光の冠","Meteorlight Crown"),ErebosSetId,"boss_erebos.head"),
            new UniqueDef("unique.boss_erebos.hands","hands.star_rings",new Txt("星雨の指環","Starshower Fingerbands"),ErebosSetId,"boss_erebos.hands"),
            new UniqueDef("unique.boss_erebos.feet","feet.star_steps",new Txt("波紋の履","Ripple Shoes"),ErebosSetId,"boss_erebos.feet"),
        };
        public static SetDef[] CreateErebosSets() => new[]
        {
            new SetDef { Id=ErebosSetId,Name=new Txt("終星の流衣","Laststar Vesture"),BossTypeName="Mon_Special_BossErebos",BossReward=ErebosRewardId,
                TwoPiece=Array.Empty<StatLine>(),ThreePiece=Array.Empty<PowerLine>(),SixPiece=Array.Empty<PowerLine>(),
                BossStages=new[] { new BossSetStage(2,"boss_erebos.stage2"),new BossSetStage(3,"boss_erebos.stage3"),new BossSetStage(6,"boss_erebos.stage6") },
                LinkStages=new[] { new SetLinkStage(2,new LinkDef { Kind=LinkKind.BossReward,Requires=new[] { "Gem_U_LastStarlight" },Value=1 }),new SetLinkStage(4,new LinkDef { Kind=LinkKind.BossReward,Requires=new[] { "Gem_U_LastStarlight" },Value=2 }),new SetLinkStage(6,new LinkDef { Kind=LinkKind.BossReward,Requires=new[] { "Gem_U_LastStarlight" },Value=3 }) } },
        };
    }
}
