using System;
using System.Collections.Generic;

namespace SodRpg.Core.Game
{
    public static partial class BossProfiles
    {
        public const string WhiteNightSetId = "set.boss_white_night";
        public const string WhiteNightRewardId = "boss_white_night.beam";
        public const string DarkMoonSetId = "set.boss_dark_moon";
        public const string DarkMoonRewardId = "boss_dark_moon.beam";
        public const string InkEventOrder = "main-start-existing-executed-palm-domain;consume-domain;white-six;white-wave;dark-form;single-target-mark;dark-chain-finish;pieces;new-white-domain;native-branch;past-success-eligible-flat;native-final-success;white-overheal-shield;independent-dark-spear;independent-illumination";
        public const string InkNativeContract = "one-parent-se-one-pooled-child-life-one-adapter;exact-native-hit-branch-checked-il-observed-once;child-only-processor-and-success-events;host-owner-parent-skill-room-run-generation;exclude-generated-reflection-summon;native-original-damage-heal-source-element-proc-steering-range-interval-endtime-timer-lock-invulnerability-unchanged;flat-add-spend-on-packet-no-refund;past-success-dwell-only-expired-slot-replacement-oldest-last-success-netid;independent-owner-global-add-spear-illumination-gates-parent-scoped-counts-budgets;freeze-spawn-H-and-magic-including-illumination-forms-marks-finishes;first-native-healed-heroes-fixed;actual-discarded-heal-only;shield-updates-spend-parent-budget;own-shield-highest-nonadditive-cap-native-initial-actual-linked-normal-reward-consumption-no-resurrection;no-native-heal-subtraction;profile-signature-independent-invalidation;unchanged-profile-ledger-container-survives-other-profile-unequip;live-current-stage-reapplication-retains-parent-tombstoned-spent-counts-owner-cooldowns-frozen-H-and-first-hero-slots-no-quota-refill;changed-profile-clears-own-dwell-marks-reservations-shields-only;terminal-removes-only-own-subscriptions-processors-containers-native-reservations-native-mark-contributions-last-source-form-chain";
        private static BossChannelDef InkChannel(string id, int value, int cap = 0, BossCoefficientKind kind = BossCoefficientKind.Damage)
            => new BossChannelDef(id, value * 1000, (cap == 0 ? value : cap) * 1000, kind);
        private static BossMoveProfile InkProfile(bool white, string id, string ja, string en, BossChannelDef[] channels, params BossAction[] actions)
            => new BossMoveProfile((white ? "boss_white_night." : "boss_dark_moon.") + id, white ? WhiteNightSetId : DarkMoonSetId, new Txt(ja, en), channels, actions);
        internal static BossMoveProfile[] CreateInkMoves() => new[]
        {
            InkProfile(true,"weapon","通常攻撃が3回命中するごとに、命中地点に0.65秒の予告後、半径2.5mに攻撃力・魔力の高い方の25%の掌撃を放つ。再使用まで3秒。", "Every 3 basic attack hits, show a warning at the hit location for 0.65 seconds, then unleash a palm strike in a 2.5m radius dealing 25% of whichever is higher: your Attack or Ability Power. Cooldown: 3 seconds.",new[]{InkChannel("LotusPalm",BossInkBalance.LotusPalmValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"LotusPalm",anchor:BossAnchor.Hit,cooldownMillis:BossInkBalance.WhiteWeaponA0CooldownMillis,delayMillis:BossInkBalance.WhiteWeaponA0DelayMillis,mainHits:BossInkBalance.WhiteWeaponA0MainHits,maxInstances:BossInkBalance.WhiteWeaponA0MaxInstances,radiusMilli:BossInkBalance.WhiteWeaponA0RadiusMilli,element:BossElement.Light)),
            InkProfile(true,"armor","被ダメージ後、自身の位置に1.5秒間、半径2mの領域を展開する。領域内にいる自身に対し、1.5秒間、攻撃力・魔力の高い方の15%分の障壁を1回付与する。再使用まで8秒。", "After you take damage, create an area with a 2m radius at your position for 1.5 seconds. While you are inside, it grants you a shield once, lasting 1.5 seconds and equal to 15% of whichever is higher: your Attack or Ability Power. Cooldown: 8 seconds.",new[]{InkChannel("LotusHaven",BossInkBalance.LotusHavenValue,kind:BossCoefficientKind.Shield)},
                new BossAction(BossEvent.NativeDamageTaken,BossMechanism.Field,BossPayload.Shield,"LotusHaven",cooldownMillis:BossInkBalance.WhiteArmorA0CooldownMillis,lifetimeMillis:BossInkBalance.WhiteArmorA0LifetimeMillis,maxInstances:BossInkBalance.WhiteArmorA0MaxInstances,maxTargets:BossInkBalance.WhiteArmorA0MaxTargets,radiusMilli:BossInkBalance.WhiteArmorA0RadiusMilli,magnitudeMilli:BossInkBalance.WhiteArmorA0MagnitudeMilli)),
            InkProfile(true,"charm","記憶を使ったとき、自身の位置に半径が3mから2mへと1.2秒かけて縮小する領域を展開する。領域の終了時、範囲内にいる自身と最も近い味方ヒーロー1人に対し、それぞれ2秒間、攻撃力・魔力の高い方の12%分の障壁を付与する。再使用まで6秒。", "When you use a memory, create an area at your position that shrinks from a 3m radius to 2m over 1.2 seconds. When it ends, grant you and the nearest allied hero inside a shield each, lasting 2 seconds and equal to 12% of whichever is higher: your Attack or Ability Power. Cooldown: 6 seconds.",new[]{InkChannel("LotusSafe",BossInkBalance.LotusSafeValue,kind:BossCoefficientKind.Shield)},
                new BossAction(BossEvent.MemoryUse,BossMechanism.Field,BossPayload.Shield,"LotusSafe",cooldownMillis:BossInkBalance.WhiteCharmA0CooldownMillis,delayMillis:BossInkBalance.WhiteCharmA0DelayMillis,lifetimeMillis:BossInkBalance.WhiteCharmA0LifetimeMillis,maxInstances:BossInkBalance.WhiteCharmA0MaxInstances,maxTargets:BossInkBalance.WhiteCharmA0MaxTargets,radiusMilli:BossInkBalance.WhiteCharmA0RadiusMilli,widthMilli:BossInkBalance.WhiteCharmA0WidthMilli,magnitudeMilli:BossInkBalance.WhiteCharmA0MagnitudeMilli)),
            InkProfile(true,"head","通常攻撃が5回命中するごとに、-30°/0°/+30°の3方向へ0秒/0.2秒/0.4秒の間隔で範囲5m・角度60°の光の扇状波を放ち、それぞれ攻撃力・魔力の高い方の10%のダメージを与える（再使用まで5秒、1連撃のみ）。", "Every 5 basic attack hits, release 3 Light waves in fans with a 5m range and a 60-degree angle, directed at -30, 0, and +30 degrees, after 0, 0.2, and 0.4 seconds respectively. Each deals 10% of whichever is higher: your Attack or Ability Power. Cooldown: 5 seconds. Only one sequence can occur at a time.",new[]{InkChannel("LotusWave",BossInkBalance.LotusWaveValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"LotusWave",BossShape.Fan,cooldownMillis:BossInkBalance.WhiteHeadA0CooldownMillis,intervalMillis:BossInkBalance.WhiteHeadA0IntervalMillis,count:BossInkBalance.WhiteHeadA0Count,mainHits:BossInkBalance.WhiteHeadA0MainHits,maxInstances:BossInkBalance.WhiteHeadA0MaxInstances,rangeMilli:BossInkBalance.WhiteHeadA0RangeMilli,angleMilli:BossInkBalance.WhiteHeadA0AngleMilli,magnitudeMilli:BossInkBalance.WhiteHeadA0MagnitudeMilli,element:BossElement.Light)),
            InkProfile(true,"hands","通常攻撃が4回命中するごとに、命中地点から2m以内にいるボス以外の行動妨害が無効でない敵を最大1m引き寄せ、0.35秒後に攻撃力・魔力の高い方の20%の掌打ダメージを与える（再使用まで4秒、地形を通過せず自身も移動しない）。", "Every 4 basic attack hits, pull enemies within 2m of the hit location up to 1m, excluding bosses and enemies immune to crowd control. After 0.35 seconds, deal palm-strike damage equal to 20% of whichever is higher: your Attack or Ability Power. Cooldown: 4 seconds. Enemies cannot pass through terrain, and you do not move.",new[]{InkChannel("LotusInch",BossInkBalance.LotusInchValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.EnemyMovement,BossPayload.Pull,anchor:BossAnchor.Hit,radiusMilli:BossInkBalance.WhiteHandsA0RadiusMilli,magnitudeMilli:BossInkBalance.WhiteHandsA0MagnitudeMilli,element:BossElement.Light),
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"LotusInch",anchor:BossAnchor.Hit,cooldownMillis:BossInkBalance.WhiteHandsA1CooldownMillis,delayMillis:BossInkBalance.WhiteHandsA1DelayMillis,mainHits:BossInkBalance.WhiteHandsA1MainHits,maxInstances:BossInkBalance.WhiteHandsA1MaxInstances,radiusMilli:BossInkBalance.WhiteHandsA1RadiusMilli,element:BossElement.Light)),
            InkProfile(true,"feet","移動完了後2秒以内に行う次の通常攻撃が命中したとき、到達地点から命中方向へ長さ6m・幅1mの直線状に攻撃力・魔力の高い方の20%のダメージを与える（再使用まで4秒）。", "When your next basic attack within 2 seconds after movement ends hits, deal damage from your arrival location toward the hit direction along a line 6m long and 1m wide, equal to 20% of whichever is higher: your Attack or Ability Power. Cooldown: 4 seconds.",new[]{InkChannel("LotusArrival",BossInkBalance.LotusArrivalValue)},
                new BossAction(BossEvent.MovementCompleted,BossMechanism.Ledger,BossPayload.ArrivalWindow,lifetimeMillis:BossInkBalance.WhiteFeetA0LifetimeMillis),
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"LotusArrival",BossShape.Line,cooldownMillis:BossInkBalance.WhiteFeetA1CooldownMillis,rangeMilli:BossInkBalance.WhiteFeetA1RangeMilli,widthMilli:BossInkBalance.WhiteFeetA1WidthMilli,element:BossElement.Light)),
            InkProfile(true,"stage2","通常攻撃が3回命中するごとに自身の位置に半径3mの白蓮領域を展開し、0.75秒後に攻撃力・魔力の高い方の40%の掌打ダメージを与える。掌打後、領域は2秒間持続し、領域内の自身と最も近い味方ヒーロー1人に攻撃力・魔力の高い方の15%の障壁を2秒間付与する（各1回、再使用まで4秒、同時に存在できる領域は1つ）。", "Every 3 basic attack hits, create a White Lotus area with a 3m radius at your position. After 0.75 seconds, deal palm-strike damage equal to 40% of whichever is higher: your Attack or Ability Power. The area then lasts 2 seconds and grants you and the nearest allied hero inside a shield once each, lasting 2 seconds and equal to 15%. Cooldown: 4 seconds. Only one area can exist at once.",new[]{InkChannel("LotusDomainPalm",BossInkBalance.LotusDomainPalmValue),InkChannel("LotusDomainShield",BossInkBalance.LotusDomainShieldValue,kind:BossCoefficientKind.Shield)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"LotusDomainPalm",cooldownMillis:BossInkBalance.WhiteStage2A0CooldownMillis,delayMillis:BossInkBalance.WhiteStage2A0DelayMillis,lifetimeMillis:BossInkBalance.WhiteStage2A0LifetimeMillis,mainHits:BossInkBalance.WhiteStage2A0MainHits,maxInstances:BossInkBalance.WhiteStage2A0MaxInstances,radiusMilli:BossInkBalance.WhiteStage2A0RadiusMilli,element:BossElement.Light),
                new BossAction(BossEvent.Clock,BossMechanism.Defense,BossPayload.Shield,"LotusDomainShield",lifetimeMillis:BossInkBalance.WhiteStage2A1LifetimeMillis,maxTargets:BossInkBalance.WhiteStage2A1MaxTargets,radiusMilli:BossInkBalance.WhiteStage2A1RadiusMilli,magnitudeMilli:BossInkBalance.WhiteStage2A1MagnitudeMilli)),
            InkProfile(true,"stage3","掌打が発動済みの自身の領域内にいる状態で通常攻撃が命中したとき、命中方向へ範囲6m・角度90°の波を放ち、攻撃力・魔力の高い方の30%のダメージを与える（再使用まで2秒。予告中やこの攻撃で新しく生成された領域は対象外）。", "When your basic attack hits while you are inside your own area where the palm strike has already occurred, release a wave toward the hit direction in a fan with a 6m range and a 90-degree angle, dealing 30% of whichever is higher: your Attack or Ability Power. Cooldown: 2 seconds. Areas still showing a warning, or created by this attack, do not qualify.",new[]{InkChannel("LotusDomainWave",BossInkBalance.LotusDomainWaveValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"LotusDomainWave",BossShape.Fan,cooldownMillis:BossInkBalance.WhiteStage3A0CooldownMillis,rangeMilli:BossInkBalance.WhiteStage3A0RangeMilli,angleMilli:BossInkBalance.WhiteStage3A0AngleMilli,element:BossElement.Light)),
            InkProfile(true,"stage6","同じ掌打発動済みの領域内にいる状態で通常攻撃が3回命中すると（波の再使用待機中もカウント）、領域を消費して半径5mに境界波を放ち攻撃力・魔力の高い方の90%のダメージを与える（上限は100%）。さらに元の領域内にいたヒーロー最大2人に、攻撃力・魔力の高い方の38%の障壁を2秒間付与する（上限は40%、再使用まで6秒。白夜セットの障壁は最大値で上書きされ、上限は攻撃力・魔力の高い方の38%）。", "After 3 basic attack hits while you are inside the same area where the palm strike has already occurred, consume it to release a boundary wave in a 5m radius, dealing 90% of whichever is higher: your Attack or Ability Power (cap: 100%). Hits during the wave cooldown also count. Also grant up to 2 heroes who were inside the original area a shield for 2 seconds equal to 38% (cap: 40%). Cooldown: 6 seconds. White Night set shields replace one another with the highest value, capped at 38% of whichever is higher: your Attack or Ability Power.",new[]{InkChannel("LotusBoundary",BossInkBalance.LotusBoundaryValue,BossInkBalance.LotusBoundaryCap),InkChannel("LotusBoundaryShield",BossInkBalance.LotusBoundaryShieldValue,BossInkBalance.LotusBoundaryShieldCap,BossCoefficientKind.Shield)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"LotusBoundary",cooldownMillis:BossInkBalance.WhiteStage6A0CooldownMillis,mainHits:BossInkBalance.WhiteStage6A0MainHits,radiusMilli:BossInkBalance.WhiteStage6A0RadiusMilli,element:BossElement.Light),
                new BossAction(BossEvent.MainHit,BossMechanism.Defense,BossPayload.Shield,"LotusBoundaryShield",lifetimeMillis:BossInkBalance.WhiteStage6A1LifetimeMillis,maxTargets:BossInkBalance.WhiteStage6A1MaxTargets,radiusMilli:BossInkBalance.WhiteStage6A1RadiusMilli,magnitudeMilli:BossInkBalance.WhiteStage6A1MagnitudeMilli)),
            InkProfile(false,"weapon","通常攻撃が3回命中するごとに、前方範囲4m・角度90°に刃を放ち、攻撃力・魔力の高い方の25%のダメージを与える（再使用まで3秒）。", "Every 3 basic attack hits, release a blade in a forward-facing fan with a 4m range and a 90-degree angle, dealing 25% of whichever is higher: your Attack or Ability Power. Cooldown: 3 seconds.",new[]{InkChannel("MoonBlade",BossInkBalance.MoonBladeValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonBlade",BossShape.Fan,cooldownMillis:BossInkBalance.DarkWeaponA0CooldownMillis,mainHits:BossInkBalance.DarkWeaponA0MainHits,rangeMilli:BossInkBalance.DarkWeaponA0RangeMilli,angleMilli:BossInkBalance.DarkWeaponA0AngleMilli,element:BossElement.Dark)),
            InkProfile(false,"armor","ダメージを受けた後、攻撃者の方向8m以内の地点に0.8秒の予告後、範囲2mに槌を叩きつけて攻撃力・魔力の高い方の20%のダメージを与える（再使用まで8秒、無敵効果なし）。", "After you take damage, show a warning for 0.8 seconds at a location within 8m toward the attacker, then slam a hammer in a 2m area, dealing 20% of whichever is higher: your Attack or Ability Power. Cooldown: 8 seconds. This does not grant invulnerability.",new[]{InkChannel("MoonWrath",BossInkBalance.MoonWrathValue)},
                new BossAction(BossEvent.NativeDamageTaken,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonWrath",anchor:BossAnchor.Hit,cooldownMillis:BossInkBalance.DarkArmorA0CooldownMillis,delayMillis:BossInkBalance.DarkArmorA0DelayMillis,maxInstances:BossInkBalance.DarkArmorA0MaxInstances,radiusMilli:BossInkBalance.DarkArmorA0RadiusMilli,rangeMilli:BossInkBalance.DarkArmorA0RangeMilli,element:BossElement.Dark)),
            InkProfile(false,"charm","記憶を使ったとき、照準方向へ弾速12m/秒で投槍を1本放ち、長さ8m・幅0.5mの軌道上の最初の敵か壁に当たるまで進んで攻撃力・魔力の高い方の20%のダメージを与える（再使用まで5秒）。", "When you use a memory, throw one spear in your aim direction at 12m/s, along a path 8m long and 0.5m wide. It stops at the first enemy or wall it hits and deals 20% of whichever is higher: your Attack or Ability Power. Cooldown: 5 seconds.",new[]{InkChannel("MoonThrow",BossInkBalance.MoonThrowValue)},
                new BossAction(BossEvent.MemoryUse,BossMechanism.Projectile,BossPayload.Damage,"MoonThrow",cooldownMillis:BossInkBalance.DarkCharmA0CooldownMillis,maxInstances:BossInkBalance.DarkCharmA0MaxInstances,rangeMilli:BossInkBalance.DarkCharmA0RangeMilli,widthMilli:BossInkBalance.DarkCharmA0WidthMilli,speedMilli:BossInkBalance.DarkCharmA0SpeedMilli,firstHitOnly:true,element:BossElement.Dark)),
            InkProfile(false,"head","通常攻撃が5回命中するごとに、命中地点（最大8m）へ弾速12m/秒の剣弾を放つ。終点の半径2mにのみ攻撃力・魔力の高い方の25%のダメージを与える（壁で消滅、再使用まで5秒、召喚物ではない）。", "Every 5 basic attack hits, fire a sword projectile at the hit location, up to 8m away, at 12m/s. It deals damage only in a 2m radius at its destination, equal to 25% of whichever is higher: your Attack or Ability Power. It disappears on hitting a wall. Cooldown: 5 seconds. This is not a summon.",new[]{InkChannel("MoonEgo",BossInkBalance.MoonEgoValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.Projectile,BossPayload.Damage,"MoonEgo",anchor:BossAnchor.Hit,cooldownMillis:BossInkBalance.DarkHeadA0CooldownMillis,mainHits:BossInkBalance.DarkHeadA0MainHits,maxInstances:BossInkBalance.DarkHeadA0MaxInstances,radiusMilli:BossInkBalance.DarkHeadA0RadiusMilli,rangeMilli:BossInkBalance.DarkHeadA0RangeMilli,widthMilli:BossInkBalance.DarkHeadA0WidthMilli,speedMilli:BossInkBalance.DarkHeadA0SpeedMilli,element:BossElement.Dark)),
            InkProfile(false,"hands","通常攻撃が4回命中するごとに、前方長さ5m・幅0.8mの直線状に攻撃力・魔力の高い方の20%のダメージを与え、ボス以外の行動妨害が無効でない敵のみを前方へ最大1m押し出す（再使用まで4秒、地形は通過しない）。", "Every 4 basic attack hits, deal damage along a forward line 5m long and 0.8m wide, equal to 20% of whichever is higher: your Attack or Ability Power, and push enemies forward up to 1m, excluding bosses and enemies immune to crowd control. Cooldown: 4 seconds. Enemies cannot pass through terrain.",new[]{InkChannel("MoonCarry",BossInkBalance.MoonCarryValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.EnemyMovement,BossPayload.Push,"MoonCarry",BossShape.Line,cooldownMillis:BossInkBalance.DarkHandsA0CooldownMillis,mainHits:BossInkBalance.DarkHandsA0MainHits,rangeMilli:BossInkBalance.DarkHandsA0RangeMilli,widthMilli:BossInkBalance.DarkHandsA0WidthMilli,magnitudeMilli:BossInkBalance.DarkHandsA0MagnitudeMilli,element:BossElement.Dark)),
            InkProfile(false,"feet","移動完了後2秒以内に行う次の通常攻撃が命中したとき、到達地点の幻影が0.4秒間予告した後、命中方向へ長さ5m・幅1mの直線状に攻撃力・魔力の高い方の25%のダメージを与える（再使用まで4秒、実体は伴わない）。", "When your next basic attack within 2 seconds after movement ends hits, an illusion at your arrival location shows a warning for 0.4 seconds, then deals damage toward the hit direction along a line 5m long and 1m wide, equal to 25% of whichever is higher: your Attack or Ability Power. Cooldown: 4 seconds. The illusion has no physical body.",new[]{InkChannel("MoonArrival",BossInkBalance.MoonArrivalValue)},
                new BossAction(BossEvent.MovementCompleted,BossMechanism.Ledger,BossPayload.ArrivalWindow,lifetimeMillis:BossInkBalance.DarkFeetA0LifetimeMillis),
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonArrival",BossShape.Line,cooldownMillis:BossInkBalance.DarkFeetA1CooldownMillis,delayMillis:BossInkBalance.DarkFeetA1DelayMillis,maxInstances:BossInkBalance.DarkFeetA1MaxInstances,rangeMilli:BossInkBalance.DarkFeetA1RangeMilli,widthMilli:BossInkBalance.DarkFeetA1WidthMilli,element:BossElement.Dark)),
            InkProfile(false,"stage2","通常攻撃が命中するごとに「刃（前方4m・角度90°に攻撃力・魔力の高い方の25%ダメージ）」→「槍（長さ7m・幅0.8mに攻撃力・魔力の高い方の25%ダメージ）」→「槌（0.6秒予告後、半径2.5mに攻撃力・魔力の高い方の40%ダメージ）」へと順に派生する（再使用時間1秒、待機中は進行・蓄積不可。刃から開始し、6秒間派生しないとリセット）。", "Basic attack hits cycle through blade, spear, and hammer in order: a forward blade with a 4m range and a 90-degree angle dealing 25% of whichever is higher: your Attack or Ability Power; a spear along a line 7m long and 0.8m wide dealing 25%; then a hammer in a 2.5m radius after a 0.6-second warning dealing 40%. Cooldown: 1 second. Hits during the cooldown cannot advance or accumulate progress. Start with the blade; reset after 6 seconds without triggering a form.",new[]{InkChannel("MoonForm",BossInkBalance.MoonFormValue),InkChannel("MoonFormHammer",BossInkBalance.MoonFormHammerValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonForm",BossShape.Fan,cooldownMillis:BossInkBalance.DarkStage2A0CooldownMillis,counterLifetimeMillis:BossInkBalance.DarkStage2A0CounterLifetimeMillis,count:BossInkBalance.DarkStage2A0Count,rangeMilli:BossInkBalance.DarkStage2A0RangeMilli,angleMilli:BossInkBalance.DarkStage2A0AngleMilli,element:BossElement.Dark),
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonForm",BossShape.Line,rangeMilli:BossInkBalance.DarkStage2A1RangeMilli,widthMilli:BossInkBalance.DarkStage2A1WidthMilli,element:BossElement.Dark),
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonFormHammer",anchor:BossAnchor.Hit,delayMillis:BossInkBalance.DarkStage2A2DelayMillis,maxInstances:BossInkBalance.DarkStage2A2MaxInstances,radiusMilli:BossInkBalance.DarkStage2A2RadiusMilli,element:BossElement.Dark)),
            InkProfile(false,"stage3","2セット効果が命中した敵1体に「月印」を付与する（最大3蓄積、持続6秒）。3蓄積時に印を消費し、0.3秒後に攻撃力・魔力の高い方の30%の斬撃ダメージを与える（再使用まで3秒。別の敵に命中させると古い印は消滅）。また、移動完了時に派生を1段階進める（再使用まで2秒、コンボはリセットされ、移動自体ではダメージは発生しない）。", "When the 2-piece effect hits, apply a Moon Mark to one enemy, lasting 6 seconds and stacking up to 3 times. At 3 stacks, consume the marks and deal slash damage after 0.3 seconds equal to 30% of whichever is higher: your Attack or Ability Power. Cooldown: 3 seconds. Hitting a different enemy removes the old marks. Also advance one form when movement ends. Cooldown: 2 seconds. This resets the combo, and movement itself deals no damage.",new[]{InkChannel("MoonMark",BossInkBalance.MoonMarkValue)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonMark",anchor:BossAnchor.Hit,cooldownMillis:BossInkBalance.DarkStage3A0CooldownMillis,delayMillis:BossInkBalance.DarkStage3A0DelayMillis,lifetimeMillis:BossInkBalance.DarkStage3A0LifetimeMillis,mainHits:BossInkBalance.DarkStage3A0MainHits,maxTargets:BossInkBalance.DarkStage3A0MaxTargets,maxInstances:BossInkBalance.DarkStage3A0MaxInstances,element:BossElement.Dark),
                new BossAction(BossEvent.MovementCompleted,BossMechanism.Ledger,BossPayload.Mode,cooldownMillis:BossInkBalance.DarkStage3A1CooldownMillis,count:BossInkBalance.DarkStage3A1Count)),
            InkProfile(false,"stage6","6秒以内に「刃→槍→槌」の連携を完了させると、槌地点の左右2mに現れる幻影から0.35秒後に長さ6m・幅0.8mの斬撃線が放たれ、それぞれ攻撃力・魔力の高い方の45%のダメージを与える（合計90%、上限は100%）。さらに0.8秒後、半径3mに攻撃力・魔力の高い方の38%の槌ダメージを与える（上限は40%、再使用まで6秒。移動で順序を飛ばすと連携はリセットされる。召喚物や実体は伴わない）。", "Complete the blade–spear–hammer combo within 6 seconds to create illusions 2m to either side of the hammer location. After 0.35 seconds, each releases a slash along a line 6m long and 0.8m wide, dealing 45% of whichever is higher: your Attack or Ability Power (90% total, cap: 100%). After a further 0.8 seconds, deal hammer damage in a 3m radius equal to 38% (cap: 40%). Cooldown: 6 seconds. Skipping a form through movement resets the combo. The illusions are not summons and have no physical bodies.",new[]{InkChannel("MoonPhantom",BossInkBalance.MoonPhantomValue,BossInkBalance.MoonPhantomCap),InkChannel("MoonFinish",BossInkBalance.MoonFinishValue,BossInkBalance.MoonFinishCap)},
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonPhantom",BossShape.Line,cooldownMillis:BossInkBalance.DarkStage6A0CooldownMillis,delayMillis:BossInkBalance.DarkStage6A0DelayMillis,counterLifetimeMillis:BossInkBalance.DarkStage6A0CounterLifetimeMillis,count:BossInkBalance.DarkStage6A0Count,maxInstances:BossInkBalance.DarkStage6A0MaxInstances,rangeMilli:BossInkBalance.DarkStage6A0RangeMilli,widthMilli:BossInkBalance.DarkStage6A0WidthMilli,magnitudeMilli:BossInkBalance.DarkStage6A0MagnitudeMilli,element:BossElement.Dark),
                new BossAction(BossEvent.MainHit,BossMechanism.ShapeAttack,BossPayload.Damage,"MoonFinish",delayMillis:BossInkBalance.DarkStage6A1DelayMillis,maxInstances:BossInkBalance.DarkStage6A1MaxInstances,radiusMilli:BossInkBalance.DarkStage6A1RadiusMilli,element:BossElement.Dark)),
        };
        internal static BossRewardProfile[] CreateInkRewards()
        {
            BossRewardStage White(int stage,int conversion,int slots,int target,int budget) => new BossRewardStage(stage,
                new Txt($"本体の光線による実際の超過回復量の{conversion/10}%を、2秒間の障壁に変換する。先着のヒーロー（自身を含む）{slots}人が対象。対象ごとの上限は攻撃力・魔力の高い方の{target/10}%、光線の詠唱1回ごとの合計上限は攻撃力・魔力の高い方の{budget/10}%（障壁の更新時も上限枠を消費）。本体の回復量は減少しない。すべての白夜セットの障壁は最大値で上書きされ、上限は攻撃力・魔力の高い方の38%。",$"Convert {conversion/10}% of the beam's actual overhealing into a shield lasting 2 seconds for the first {slots} heroes, including you. Each hero's shield is capped at {target/10}% of whichever is higher: your Attack or Ability Power. The total shield allowance per beam cast is {budget/10}% of that value; shield updates also use this allowance. The beam's healing is not reduced. All White Night set shields replace one another with the highest value, capped at 38% of whichever is higher: your Attack or Ability Power."),
                new[]{new BossRewardAction(BossRewardActionKind.NativeShield,conversion,conversion,durationMillis:BossInkBalance.WhiteShieldDurationMillis,count:slots,targetCapMilli:target,budgetMilli:budget)});
            BossRewardStage Dark(int stage,int dwell,int flat,int budget)
            {
                var actions = new List<BossRewardAction>{new BossRewardAction(BossRewardActionKind.NativeDamage,flat,flat,BossInkBalance.DarkCooldownMillis,count:BossInkBalance.DarkCount,dwellMillis:dwell,gapToleranceMillis:BossInkBalance.DarkGapToleranceMillis,budgetMilli:budget,magnitudeMilli:BossInkBalance.DarkMagnitude)};
                if(stage>=2) actions.Add(new BossRewardAction(BossRewardActionKind.NativeTarget,BossInkBalance.DarkSpearValue,BossInkBalance.DarkSpearValue,BossInkBalance.DarkSpearCooldownMillis,count:BossInkBalance.DarkSpearCount,rangeMilli:BossInkBalance.DarkSpearRangeMilli,order:1,speedMilli:BossInkBalance.DarkSpearSpeedMilli,widthMilli:BossInkBalance.DarkSpearWidthMilli));
                if(stage>=3) actions.Add(new BossRewardAction(BossRewardActionKind.NativeMode,cooldownMillis:BossInkBalance.DarkModeCooldownMillis,count:BossInkBalance.DarkModeCount,order:2));
                return new BossRewardStage(stage,new Txt($"同じ敵に本体の光線が連続で{dwell/1000.0:0.##}秒間命中した後、その敵への次の光線ダメージに攻撃力・魔力の高い方の{flat/10}%の追加ダメージを与える（再使用まで1秒、光線1回につき最大3回まで・合計上限{budget/10}%、最大3体の敵まで）。"+(stage>=2?"また、光線命中時に継続時間とは独立して投槍（弾速12m/秒、長さ8m・幅0.5m、攻撃力・魔力の高い方の25%ダメージ）を放つ（再使用まで1秒、光線1回につき最大3本）。":"")+(stage>=3?"さらに光線命中時に独立して通常攻撃扱いの2セット派生を放つ（再使用まで1秒、光線1回につき最大6回。2セット効果と再使用時間を共有し、派生・月印・コンボのみを進行させ、部位装備の攻撃回数はカウントされない）。":""),$"After the beam hits the same enemy continuously for {dwell/1000.0:0.##} seconds, its next damage to that enemy deals additional damage equal to {flat/10}% of whichever is higher: your Attack or Ability Power. Cooldown: 1 second. Each beam cast can trigger this up to 3 times, with a total cap of {budget/10}%, for up to 3 enemies. "+(stage>=2?"Also, when the beam hits, independently of the continuous-hit duration, throw a spear at 12m/s along a path 8m long and 0.5m wide, dealing 25% of whichever is higher: your Attack or Ability Power. Cooldown: 1 second, up to 3 spears per beam cast. ":"")+(stage>=3?"Also, when the beam hits, independently trigger a 2-piece attack form treated as a basic attack. Cooldown: 1 second, shared with the 2-piece effect, up to 6 times per beam cast. This advances only attack forms, Moon Marks, and the combo; it does not count toward equipment-piece attack counters.":"")),actions);
            }
            return new[]{new BossRewardProfile(WhiteNightRewardId,WhiteNightSetId,"St_U_BeamOfBalance",BossRewardAdapter.BeamOfBalance,new[]{White(1,BossInkBalance.RewardWhiteStage1Conversion,BossInkBalance.RewardWhiteStage1Slots,BossInkBalance.RewardWhiteStage1Target,BossInkBalance.RewardWhiteStage1Budget),White(2,BossInkBalance.RewardWhiteStage2Conversion,BossInkBalance.RewardWhiteStage2Slots,BossInkBalance.RewardWhiteStage2Target,BossInkBalance.RewardWhiteStage2Budget),White(3,BossInkBalance.RewardWhiteStage3Conversion,BossInkBalance.RewardWhiteStage3Slots,BossInkBalance.RewardWhiteStage3Target,BossInkBalance.RewardWhiteStage3Budget)}),new BossRewardProfile(DarkMoonRewardId,DarkMoonSetId,"St_U_BeamOfBalance",BossRewardAdapter.BeamOfBalance,new[]{Dark(1,BossInkBalance.RewardDarkStage1DwellMillis,BossInkBalance.RewardDarkStage1Flat,BossInkBalance.RewardDarkStage1Budget),Dark(2,BossInkBalance.RewardDarkStage2DwellMillis,BossInkBalance.RewardDarkStage2Flat,BossInkBalance.RewardDarkStage2Budget),Dark(3,BossInkBalance.RewardDarkStage3DwellMillis,BossInkBalance.RewardDarkStage3Flat,BossInkBalance.RewardDarkStage3Budget)})};
        }
        public static UniqueDef[] CreateInkPieces()
        {
            var result = new List<UniqueDef>();
            void Add(string set,string slot,string baseId,string ja,string en) => result.Add(new UniqueDef(set+"."+slot,baseId,new Txt(ja,en),set,set.Substring(4)+"."+slot));
            Add(WhiteNightSetId,"weapon","weapon.pilgrim_staff","白蓮の錫杖","White Lotus Staff");
            Add(WhiteNightSetId,"armor","armor.prayer_shawl","安息域の法衣","Haven Robe");
            Add(WhiteNightSetId,"charm","charm.lotus_seal","光秤の印","Lightscale Seal");
            Add(WhiteNightSetId,"head","head.radiant_halo","白暁の冠","White Dawn Crown");
            Add(WhiteNightSetId,"hands","hands.radiant_wraps","蓮掌の手巻き","Lotus Palm Wraps");
            Add(WhiteNightSetId,"feet","feet.dawn_steps","光界の歩み","Lightward Steps");
            Add(DarkMoonSetId,"weapon","weapon.tide_trident","黒月の三叉刃","Black Moon Trident");
            Add(DarkMoonSetId,"armor","armor.shadow_cloak","怒影の鎧","Wrathshadow Mail");
            Add(DarkMoonSetId,"charm","charm.shadow_ring","月欠けの環","Waning Moon Ring");
            Add(DarkMoonSetId,"head","head.raven_mask","自我の面","Mask of the Self");
            Add(DarkMoonSetId,"hands","hands.shadow_gloves","切替の握り","Shifting Grips");
            Add(DarkMoonSetId,"feet","feet.shadow_slippers","跳影の靴","Shadowleap Boots");
            return result.ToArray();
        }
        public static SetDef[] CreateInkSets()
        {
            SetDef Set(string id,string ja,string en,string boss,string reward) => new SetDef
            {
                Id=id,Name=new Txt(ja,en),BossTypeName=boss,BossReward=reward,
                TwoPiece=Array.Empty<StatLine>(),ThreePiece=Array.Empty<PowerLine>(),SixPiece=Array.Empty<PowerLine>(),
                BossStages=new[]{new BossSetStage(2,id.Substring(4)+".stage2"),new BossSetStage(3,id.Substring(4)+".stage3"),new BossSetStage(6,id.Substring(4)+".stage6")},
                LinkStages=new[]
                {
                    new SetLinkStage(2,new LinkDef{Kind=LinkKind.BossReward,Value=1,Requires=new[]{"St_U_BeamOfBalance"}}),
                    new SetLinkStage(4,new LinkDef{Kind=LinkKind.BossReward,Value=2,Requires=new[]{"St_U_BeamOfBalance"}}),
                    new SetLinkStage(6,new LinkDef{Kind=LinkKind.BossReward,Value=3,Requires=new[]{"St_U_BeamOfBalance"}}),
                },
            };
            return new[]{Set(WhiteNightSetId,"白蓮の守装","White Lotus Vestments","Mon_Ink_BossWhiteNight",WhiteNightRewardId),Set(DarkMoonSetId,"黒月の刃装","Black Moon Armament","Mon_Ink_BossDarkMoon",DarkMoonRewardId)};
        }
    }
}
