using System;

namespace SodRpg.Core.Game
{
    public static partial class BossProfiles
    {
        public const string SeekerSetId = "set.boss_seeker";
        public const string SeekerRewardId = "boss_seeker.soul_prison";
        public const string SeekerNativeContract = "exact-DeathInterrupt-callback-and-quality-native-heal;final-native-heal-plus-min10percent-.20H;one-native-dispatch;preserve-discarded-native-infinite-shield-HP1-consumption-invulnerability;overflow-self25percent-cap.30H-6s-ally25percent-cap.40H-3s-nearest-alive-allied-hero6m-excluding-self;confirmed-native-consumption-retains-finite-shields;manual-reduction-death-room-clears;actor-parent-gem-skill-pool-life-room-run-gear-guards";
        public const string SeekerEventOrder = "E1-advance-green-purple-red-once-even-during-CD;phase-shot-CD3;existing-stage3-double-copies-current-phase-once-then-disappears;parts;E3-departure-only-shared-single-nonEntity-double;E2-fixed-claw-fan-three-pulses-and-once-shield";
        private static BossChannelDef SeekerChannel(string id,int value,int cap,BossCoefficientKind kind=BossCoefficientKind.Damage) => new BossChannelDef(id,value*1000,cap*1000,kind);
        private static BossMoveProfile SeekerProfile(string id,string ja,string en,BossChannelDef[] channels,params BossAction[] actions) => new BossMoveProfile("boss_seeker."+id,SeekerSetId,new Txt(ja,en),channels,actions);
        private static BossAction SeekerOrb(BossEvent kind,string channel,int cd,int life=1000,int speed=8000) => new BossAction(kind,BossMechanism.Projectile,BossPayload.Damage,channel,BossShape.Circle,BossAnchor.Hit,cooldownMillis:cd,lifetimeMillis:life,maxInstances:1,radiusMilli:1500,rangeMilli:8000,widthMilli:400,speedMilli:speed,firstHitOnly:true);
        internal static BossMoveProfile[] CreateSeekerMoves() => new[]
        {
            SeekerProfile("weapon","通常攻撃命中時、主対象の位置へ球を1発発射する（射程8m、持続1秒）。到達時に半径1.5mの爆発を起こし、攻撃力・魔力の高い方の18%のダメージを与える（上限54）。再使用まで3秒（壁に衝突しても爆発しない）。","A native main hit fires one orb at the fixed main-target point: range8m, lifetime1s, terminal1.5m explosion18%H(cap54), CD3s; no wall explosion.",new[]{SeekerChannel("SeekerOrb",18,54)},SeekerOrb(BossEvent.MainHit,"SeekerOrb",3000)),
            SeekerProfile("armor","被ダメージ時、自身の位置に分身を1体出現させ（持続2秒）、自身に2秒間、攻撃力・魔力の高い方の18%分の障壁を付与する（上限54）。再使用まで10秒（3部位効果の分身と合わせて同時に最大1体まで存在可能、挑発や敵の標的変更効果なし）。","Native damage taken displays one non-Entity double at your position for2s and grants18%H self shield(cap54)/2s, CD10s. Shared max1 with3-piece double; no taunt or target changes.",new[]{SeekerChannel("SeekerDoubleGuard",18,54,BossCoefficientKind.Shield)},new BossAction(BossEvent.NativeDamageTaken,BossMechanism.Defense,BossPayload.Shield,"SeekerDoubleGuard",cooldownMillis:10000,lifetimeMillis:2000,maxInstances:1)),
            SeekerProfile("charm","記憶を使ったとき、8m以内の最も近い敵へ誘導弾を1発放つ（持続2秒、最大移動8m）。命中時または消滅時に半径1.5mの範囲へ攻撃力・魔力の高い方の24%（上限72）のダメージを与える。再使用まで6秒。","Confirmed normal/ultimate memory use fires one homing orb at the nearest enemy within8m:2s lifetime,8m travel cap, one1.5m explosion24%H(cap72) on hit or expiration, CD6s.",new[]{SeekerChannel("SeekerChaser",24,72)},SeekerOrb(BossEvent.MemoryUse,"SeekerChaser",6000,2000,4000)),
            SeekerProfile("head","通常攻撃命中時、8m以内の対象地点に0.4秒の予告後、半径2mの範囲へ攻撃力・魔力の高い方の20%（上限60）のダメージを与える。再使用まで5秒（画面暗転なし）。","A native main hit warns the fixed main-target point within8m for0.4s, then20%H(cap60) in2m, CD5s; no screen darkening.",new[]{SeekerChannel("SeekerAim",20,60)},new BossAction(BossEvent.MainHit,BossMechanism.Field,BossPayload.Damage,"SeekerAim",BossShape.Circle,BossAnchor.Hit,cooldownMillis:5000,delayMillis:400,maxInstances:1,radiusMilli:2000,rangeMilli:8000)),
            SeekerProfile("hands","記憶を使ったとき、8m以内の最も近い敵の位置に2秒間持続する半径2mの紫の領域を生成する（敵を追従せず、子領域も生成しない）。0.5秒後と1.5秒後にそれぞれ攻撃力・魔力の高い方の10%（上限30）のダメージを与える。再使用まで6秒。","Confirmed memory use fixes the nearest enemy point within8m: one2m purple field for2s,10%H(cap30) at0.5/1.5s, CD6s. No following or child fields.",new[]{SeekerChannel("SeekerPurple",10,30)},new BossAction(BossEvent.MemoryUse,BossMechanism.Field,BossPayload.Damage,"SeekerPurple",BossShape.Circle,BossAnchor.Hit,cooldownMillis:6000,delayMillis:500,lifetimeMillis:2000,intervalMillis:1000,count:2,maxInstances:1,radiusMilli:2000,rangeMilli:8000)),
            SeekerProfile("feet","移動完了時（強制移動や自動生成された移動を除く）、移動前の位置に0.3秒の予告後、半径1.5mの範囲へ攻撃力・魔力の高い方の22%（上限66）の火属性ダメージを与え、ボスと行動妨害が無効な敵以外を0.25秒スタンさせる。再使用まで5秒。","Native owner movement completion warns the departure point for0.3s, then22%H Fire(cap66) in1.5m and0.25s stun only to non-boss, non-CC-immune enemies, CD5s; generated movement excluded.",new[]{SeekerChannel("SeekerFissure",22,66)},new BossAction(BossEvent.MovementCompleted,BossMechanism.Field,BossPayload.Damage,"SeekerFissure",cooldownMillis:5000,delayMillis:300,maxInstances:1,radiusMilli:1500,magnitudeMilli:250,element:BossElement.Fire)),
            SeekerProfile("stage2","通常攻撃命中時、現在の位相に応じた追加攻撃を行い（攻撃力・魔力の高い方の16%、再使用まで3秒）、位相を緑→紫→赤へと1段階進める（再使用待機中も命中ごとに進行、1回の攻撃につき1段階まで）。緑：8mを1秒で飛ぶ球、紫：対象地点に0.4秒予告後半径1.5mへ攻撃、赤：同地点の半径1.5mへ火属性即時攻撃。","Each successful native main activation advances green→purple→red once, even during CD. Phase attack16%H, CD3s: green8m/1s orb; purple fixed-target0.4s warning/1.5m; red same1.5m point with Fire.",new[]{SeekerChannel("SeekerPhase",16,16)},SeekerOrb(BossEvent.MainHit,"SeekerPhase",3000),new BossAction(BossEvent.Clock,BossMechanism.Field,BossPayload.Damage,"SeekerPhase",BossShape.Circle,BossAnchor.Hit,delayMillis:400,maxInstances:1,radiusMilli:1500,rangeMilli:8000),new BossAction(BossEvent.Clock,BossMechanism.ShapeAttack,BossPayload.Damage,"SeekerPhase",BossShape.Circle,BossAnchor.Hit,maxInstances:1,radiusMilli:1500,rangeMilli:8000,element:BossElement.Fire)),
            SeekerProfile("stage3","移動完了時、移動前の位置に3秒間分身を1体残す（再使用まで5秒、防具効果の分身と合わせて同時に最大1体、召喚扱いなし）。次の通常攻撃命中時、分身の位置から主対象地点（射程8m）へ現在の位相攻撃を複製して攻撃力・魔力の高い方の12%のダメージを与え、分身は消滅する。","Native movement completion leaves one non-Entity double at departure for3s, CD5s. The next main hit copies its phase once from the double to the fixed target for12%H/range8m, then vanishes. Shared max1 with Armor; no summon proc/loot.",new[]{SeekerChannel("SeekerEcho",12,12)},new BossAction(BossEvent.MovementCompleted,BossMechanism.Deployable,BossPayload.Deploy,"SeekerEcho",cooldownMillis:5000,lifetimeMillis:3000,maxInstances:1,rangeMilli:8000)),
            SeekerProfile("stage6","記憶を使ったとき、8m以内の敵の位置を狙い、0.5秒・0.75秒・1秒後に射程4m・角度90度の扇状爪撃を放ち、それぞれ攻撃力・魔力の高い方の30%（合計90%/上限100）のダメージを与える。さらに自身に2.5秒間、攻撃力・魔力の高い方の38%（上限40）の障壁を付与する。再使用まで10秒（発動中も操作可能、無敵化や画面暗転なし）。","Confirmed memory use fixes an enemy point within8m; at0.5/0.75/1s three4m/90-degree claw fans each deal30%H(total90/cap100), plus one38%H self shield(cap40)/2.5s, CD10s. No control block, invulnerability or darkening.",new[]{SeekerChannel("SeekerClaws",90,100),SeekerChannel("SeekerClawGuard",38,40,BossCoefficientKind.Shield)},new BossAction(BossEvent.MemoryUse,BossMechanism.Field,BossPayload.Damage,"SeekerClaws",BossShape.Fan,BossAnchor.Hit,cooldownMillis:10000,delayMillis:500,intervalMillis:250,count:3,maxInstances:1,rangeMilli:4000,angleMilli:90000,magnitudeMilli:8000),new BossAction(BossEvent.Clock,BossMechanism.Defense,BossPayload.Shield,"SeekerClawGuard",lifetimeMillis:2500,maxInstances:1))
        };
        internal static BossRewardProfile[] CreateSeekerRewards()
        {
            BossRewardAction Heal()=>new BossRewardAction(BossRewardActionKind.NativeHeal,10000,10000,magnitudeMilli:20000);
            BossRewardAction Self()=>new BossRewardAction(BossRewardActionKind.NativeShield,25000,25000,durationMillis:6000,order:1,targetCapMilli:30000);
            return new[]{new BossRewardProfile(SeekerRewardId,SeekerSetId,"Gem_U_SoulPrison",BossRewardAdapter.SoulPrison,new[]{
                new BossRewardStage(1,new Txt("宝石「魂の牢獄」による救命効果発動時、品質倍率適用後の最終回復量に、元の回復量の10%または攻撃力・魔力の高い方の20%のいずれか低い方を加算する（別の回復は発生せず、HP1耐え・元の超過回復・宝石消費・無敵時間は変化しない）。","Only the native rescue's final quality-scaled heal gains min(original10%,0.20H). No second heal; preserve HP1, native overflow, consumption and invulnerability."),new[]{Heal()}),
                new BossRewardStage(2,new Txt("段階1の効果に加え、「魂の牢獄」の救命回復の超過分の25%にあたる追加の障壁（上限：攻撃力・魔力の高い方の30%、持続6秒）を自身に付与する（元の超過回復と同量の無期限障壁もそのまま維持される）。","Stage1 plus once grant an extra self shield of25% rescue overflow(cap0.30H)/6s; preserve native full-overflow infinite shield."),new[]{Heal(),Self()}),
                new BossRewardStage(3,new Txt("段階2の効果に加え、「魂の牢獄」の救命回復の超過分の25%にあたる障壁（上限：攻撃力・魔力の高い方の40%、持続3秒）を、6m以内の最も近くにいる生存中の味方ヒーロー1人（自身を除く）に付与する（宝石消費後も効果時間中は維持されるが、装備解除・死亡・部屋移動で消滅。無敵延長なし）。","Stage2 plus once shield nearest alive allied Hero within6m, excluding self, for25% rescue overflow(cap0.40H)/3s. Confirmed consumption preserves finite shields until expiry; voluntary gear removal, death or room change clears them. No invulnerability extension."),new[]{Heal(),Self(),new BossRewardAction(BossRewardActionKind.NativeShield,25000,25000,durationMillis:3000,rangeMilli:6000,order:2,targetCapMilli:40000)})})};
        }
        public static UniqueDef[] CreateSeekerPieces()=>new[]{
            new UniqueDef("unique.boss_seeker.weapon","weapon.dream_wand",new Txt("幻彩の球杖","Mirage Orb Rod"),SeekerSetId,"boss_seeker.weapon"),
            new UniqueDef("unique.boss_seeker.armor","armor.mirrorsilk_robe",new Txt("分身の外套","Double Mantle"),SeekerSetId,"boss_seeker.armor"),
            new UniqueDef("unique.boss_seeker.charm","charm.pulsing_core",new Txt("魂窓の珠","Soulwindow Pearl"),SeekerSetId,"boss_seeker.charm"),
            new UniqueDef("unique.boss_seeker.head","head.moth_wing_mask",new Txt("狭界の面","Narrowworld Mask"),SeekerSetId,"boss_seeker.head"),
            new UniqueDef("unique.boss_seeker.hands","hands.shadow_gloves",new Txt("紫影の手袋","Violetshadow Gloves"),SeekerSetId,"boss_seeker.hands"),
            new UniqueDef("unique.boss_seeker.feet","feet.ember_treads",new Txt("裂け目の歩み","Fissure Steps"),SeekerSetId,"boss_seeker.feet")};
        public static SetDef[] CreateSeekerSets()=>new[]{new SetDef{Id=SeekerSetId,Name=new Txt("幻彩の追装","Mirage Spectrum Gear"),BossTypeName="Mon_DarkCave_BossSeeker",TwoPiece=Array.Empty<StatLine>(),ThreePiece=Array.Empty<PowerLine>(),SixPiece=Array.Empty<PowerLine>(),BossStages=new[]{new BossSetStage(2,"boss_seeker.stage2"),new BossSetStage(3,"boss_seeker.stage3"),new BossSetStage(6,"boss_seeker.stage6")},BossReward=SeekerRewardId,LinkStages=new[]{new SetLinkStage(2,new LinkDef{Kind=LinkKind.BossReward,Value=1,Requires=new[]{"Gem_U_SoulPrison"}}),new SetLinkStage(4,new LinkDef{Kind=LinkKind.BossReward,Value=2,Requires=new[]{"Gem_U_SoulPrison"}}),new SetLinkStage(6,new LinkDef{Kind=LinkKind.BossReward,Value=3,Requires=new[]{"Gem_U_SoulPrison"}})}}};
    }
}
