// <auto-generated />
// Source: tools/balance/gear.json
namespace SodRpg.Core.Game
{
    public static class GearBalance
    {
        public const int MaxItemLevel = 60;
        public const int ItemLevelScalingCap = 40;
        public const int BaseLevelScalePct = 100;
        public const int FlatDamageGrowthPct = 5;
        public const int OtherFixedGrowthPct = 3;
        public const string ContentFingerprintRecord = "balance:gear:v1:{\"AttackFlatCap\":250,\"BaseLevelScalePct\":100,\"FlatDamageGrowthPct\":5,\"ItemLevelScalingCap\":40,\"MaxItemLevel\":60,\"OtherFixedGrowthPct\":3,\"PowerFlatCap\":250,\"schemaVersion\":1}";
    }
}
