// <auto-generated />
// Sources: tools/balance/stars.json, tools/balance/run-growth.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class StarRankBalance
    {
        internal const decimal DamagePerPoint = 0.003m;
        internal const decimal MaxMultiplier = 2.512m;
        internal const int MaxPoints = 504;
        internal const int EssenceSlotsMaxAdded = 8;
        internal const int EssenceSlotsMaxPerLocation = 4;
        internal const int EssenceSlotStarAmount = 1;
        internal static readonly string ContentFingerprintRecord = "balance:stars:rank:v1|gain:1.5|denominator:500|maxPoints:504|growth:cetus.run.choice/options/0/growth/capBonus:milli:0|cetus.run.choice/options/1/growth/capBonus:milli:0|cetus.run.g1/growth/cap:milli:60000|cetus.run.g1/growth/effects/0/amount:milli:500|cetus.run.g1/growth/effects/1/amount:milli:5000|cetus.run.g1/growth/threshold:milli:9000|cetus.run.m1/growth/capBonus:milli:20000|cetus.run.m2/growth/capBonus:milli:20000|husk.run.choice/options/0/growth/capBonus:milli:0|husk.run.choice/options/1/growth/capBonus:milli:0|husk.run.g1/growth/cap:milli:45000|husk.run.g1/growth/effects/0/amount:milli:1380|husk.run.g1/growth/threshold:milli:1000|husk.run.m1/growth/capBonus:milli:12000|husk.run.m2/growth/capBonus:milli:12000|mist.run.choice/options/0/growth/capBonus:milli:0|mist.run.choice/options/1/growth/capBonus:milli:0|mist.run.g1/growth/cap:milli:60000|mist.run.g1/growth/effects/0/amount:milli:1000|mist.run.g1/growth/effects/1/amount:milli:300|mist.run.g1/growth/threshold:milli:1000|mist.run.m1/growth/capBonus:milli:20000|mist.run.m2/growth/capBonus:milli:20000|vesper.run.choice/options/0/growth/capBonus:milli:0|vesper.run.choice/options/1/growth/capBonus:milli:0|vesper.run.g1/growth/cap:milli:60000|vesper.run.g1/growth/effects/0/amount:milli:1000|vesper.run.g1/growth/effects/1/amount:milli:4000|vesper.run.g1/growth/threshold:milli:11000|vesper.run.m1/growth/capBonus:milli:20000|vesper.run.m2/growth/capBonus:milli:20000";
    }
}
