// <auto-generated />
// Source: tools/balance/bosses/*.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class BossBalanceValues
    {
        internal static readonly bool MatchesFrozenReference = true;
    }
}
