// <auto-generated />
// Source: tools/balance/bosses/azurak.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class BossAzurakBalance
    {
        internal const int RoarDoubleValue = 18;
        internal const int WeaponA0CooldownMillis = 4000;
        internal const int WeaponA0IntervalMillis = 150;
        internal const int WeaponA0Count = 2;
        internal const int WeaponA0MaxInstances = 1;
        internal const int WeaponA0RadiusMilli = 2500;
        internal const int RoarRampartValue = 10;
        internal const int ArmorA0CooldownMillis = 6000;
        internal const int ArmorA0LifetimeMillis = 2000;
        internal const int ArmorA0MaxTargets = 1;
        internal const int ArmorA0MaxInstances = 1;
        internal const int RoarCallValue = 14;
        internal const int CharmA0CooldownMillis = 6000;
        internal const int CharmA0MaxInstances = 1;
        internal const int CharmA0RadiusMilli = 3000;
        internal const int CharmA0MagnitudeMilli = 800;
        internal const int RoarHavenValue = 8;
        internal const int HeadA0CooldownMillis = 6000;
        internal const int HeadA0DelayMillis = 500;
        internal const int HeadA0LifetimeMillis = 1000;
        internal const int HeadA0MaxInstances = 1;
        internal const int HeadA0MaxTargets = 1;
        internal const int HeadA0RadiusMilli = 2000;
        internal const int HeadA1LifetimeMillis = 1500;
        internal const int HeadA1MaxTargets = 1;
        internal const int RoarArtilleryValue = 18;
        internal const int HandsA0CooldownMillis = 5000;
        internal const int HandsA0DelayMillis = 600;
        internal const int HandsA0MaxInstances = 1;
        internal const int HandsA0RadiusMilli = 1500;
        internal const int HandsA0RangeMilli = 8000;
        internal const int RoarLandingValue = 16;
        internal const int FeetA0CooldownMillis = 5000;
        internal const int FeetA0MaxInstances = 1;
        internal const int FeetA0RadiusMilli = 2000;
        internal const int RoarQuakeValue = 16;
        internal const int Stage2A0CooldownMillis = 3000;
        internal const int Stage2A0MainHits = 3;
        internal const int Stage2A0CounterLifetimeMillis = 4000;
        internal const int Stage2A0MaxInstances = 1;
        internal const int Stage2A0RadiusMilli = 2500;
        internal const int Stage2A0RangeMilli = 8000;
        internal const int RoarRestompValue = 22;
        internal const int Stage3A0CooldownMillis = 5000;
        internal const int Stage3A0DelayMillis = 450;
        internal const int Stage3A0MaxInstances = 1;
        internal const int Stage3A0RadiusMilli = 2500;
        internal const int Stage3A0RangeMilli = 8000;
        internal const int RoarGrandDoubleValue = 90;
        internal const int RoarGrandDoubleCap = 100;
        internal const int RoarGrandShieldValue = 38;
        internal const int RoarGrandShieldCap = 40;
        internal const int Stage6A0CooldownMillis = 8000;
        internal const int Stage6A0DelayMillis = 350;
        internal const int Stage6A0IntervalMillis = 200;
        internal const int Stage6A0Count = 2;
        internal const int Stage6A0MaxInstances = 1;
        internal const int Stage6A0RadiusMilli = 3000;
        internal const int Stage6A0RangeMilli = 8000;
        internal const int Stage6A1LifetimeMillis = 3000;
        internal const int Stage6A1MaxTargets = 1;
        internal const int RewardExtendValueMilli = 150;
        internal const int RewardExtendCapMilli = 150;
        internal const int RewardExtendDurationMillis = 1000;
        internal const int RewardDamageStage2ValueMilli = 200;
        internal const int RewardDamageStage3ValueMilli = 250;
        internal const int RewardDamageCooldownMillis = 8000;
        internal const int RewardDamageStage2BudgetMilli = 200;
        internal const int RewardDamageStage3BudgetMilli = 450;
        internal const int RewardShortenValueMilli = 50;
        internal const int RewardShortenCapMilli = 50;
    }
}
