// <auto-generated />
// Source: tools/balance/boss-sets.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class BossSetsBalance
    {
        internal const int NormalDropPercent = 10;
        internal const int NightmareBonusPercent = 5;
        internal const int DepthBonusPercent = 1;
        internal const int MaxDropDepth = 5;
        internal const int MaxDropPercent = 20;
        // Existing ContentFingerprint boss-drop record includes all five adopted values.
        internal static readonly string ContentFingerprintRecord = null;
    }
}
