// <auto-generated />
// Source: tools/balance/bosses/demon.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class BossDemonBalance
    {
        internal const int BudDelayMillis = 1200;
        internal const int BudCollectibleDelayMillis = 150;
        internal const int BudRadiusMilli = 2500;
        internal const int MaxBuds = 4;
        internal const int NativeHysteriaSpeedMilli = -50000;
        internal const int BudRangeMilli = 8000;
        internal const int DemonImpactValue = 25;
        internal const int DemonImpactCap = 80;
        internal const int WeaponA0CooldownMillis = 2000;
        internal const int WeaponA0MainHits = 3;
        internal const int WeaponA0RadiusMilli = 3000;
        internal const int DemonStrideValue = 6;
        internal const int DemonStrideCap = 10;
        internal const int ArmorA0CooldownMillis = 8000;
        internal const int ArmorA0LifetimeMillis = 600;
        internal const int DemonSeedValue = 20;
        internal const int DemonSeedCap = 60;
        internal const int CharmA0CooldownMillis = 4000;
        internal const int DemonVolleyValue = 12;
        internal const int DemonVolleyCap = 40;
        internal const int HeadA0CooldownMillis = 6000;
        internal const int HeadA0LifetimeMillis = 500;
        internal const int HeadA0Count = 6;
        internal const int HeadA0MainHits = 6;
        internal const int HeadA0RangeMilli = 6000;
        internal const int HeadA0WidthMilli = 400;
        internal const int HeadA0SpeedMilli = 12000;
        internal const int HeadA0AngleMilli = 60000;
        internal const int DemonDelayValue = 25;
        internal const int DemonDelayCap = 80;
        internal const int HandsA0CooldownMillis = 3000;
        internal const int HandsA0DelayMillis = 650;
        internal const int HandsA0LifetimeMillis = 650;
        internal const int HandsA0MainHits = 4;
        internal const int HandsA0RadiusMilli = 2000;
        internal const int DemonArrivalValue = 20;
        internal const int DemonArrivalCap = 60;
        internal const int FeetA0LifetimeMillis = 3000;
        internal const int FeetA1CooldownMillis = 4000;
        internal const int FeetA1RadiusMilli = 3000;
        internal const int DemonStompValue = 50;
        internal const int DemonStompCap = 100;
        internal const int Stage2A0CooldownMillis = 3000;
        internal const int Stage2A0RadiusMilli = 3000;
        internal const int DemonGroveValue = 45;
        internal const int DemonGroveCap = 90;
        internal const int Stage3A0CooldownMillis = 1000;
        internal const int Stage3A0RangeMilli = 4000;
        internal const int Stage3A1CooldownMillis = 1000;
        internal const int Stage3A1RangeMilli = 8000;
        internal const int Stage3A2CooldownMillis = 1000;
        internal const int DemonMarchValue = 90;
        internal const int DemonMarchCap = 100;
        internal const int DemonReplantValue = 38;
        internal const int DemonReplantCap = 40;
        internal const int Stage6A0CooldownMillis = 6000;
        internal const int Stage6A0IntervalMillis = 250;
        internal const int Stage6A0Count = 3;
        internal const int Stage6A0RadiusMilli = 2500;
        internal const int Stage6A0RangeMilli = 8000;
        internal const int Stage6A0MaxInstances = 4;
        internal const int Stage6A0MagnitudeMilli = 6000;
        internal const int Stage6A1Count = 2;
        internal const int RewardPairCooldownMillis = 3000;
        internal const int RewardPairCount = 2;
        internal const int RewardPlantValueMilli = 45000;
        internal const int RewardPlantCapMilli = 90000;
        internal const int RewardPlantCooldownMillis = 1000;
        internal const int RewardPlantCount = 1;
        internal const int RewardPlantRangeMilli = 8000;
        internal const int RewardCollectCooldownMillis = 1000;
        internal const int RewardCollectRangeMilli = 4000;
        internal const int RewardMarchCooldownMillis = 6000;
        internal const int RewardMarchRangeMilli = 8000;
        internal const int RewardNativeSpeedValueMilli = -25000;
        internal const int RewardNativeSpeedCapMilli = 50000;
    }
}
