// <auto-generated />
// Source: tools/balance/daily-dream.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class DailyDreamBalance
    {
        internal const int PowerBoostPct = 50;
        internal const double Day4ShardMult = 1.5d;
        internal const double Day5DropBonus = 0.25d;
        internal const double Day6NightmareMult = 2d;
        internal const double Day7XpMult = 1.3d;
        internal const double Day8BountyMult = 2d;
        internal const double Day13XpMult = 1.5d;
        internal const double Day14BountyMult = 1.5d;
        internal const double Day14ShardMult = 1.25d;
        internal const double Day21DropBonus = 0.2d;
        internal const double Day21ShardMult = 1.2d;
        internal const double Day22NightmareMult = 1.5d;
        internal const double Day22XpMult = 1.2d;
        internal const double Day23DropBonus = 0.35d;
        internal const double Day24XpMult = 1.3d;
        internal const double Day24BountyMult = 1.5d;
        internal const double Day25ShardMult = 1.6d;
        internal const double Day26BountyMult = 1.5d;
        internal const double Day26DropBonus = 0.1d;
        internal const double Day30NightmareMult = 1.5d;
        internal const double Day30DropBonus = 0.25d;
        internal const double Day46ShardMult = 1.4d;
        internal const double Day46DropBonus = 0.15d;
        internal const double Day47XpMult = 1.4d;
        internal const double Day47NightmareMult = 1.25d;
        internal const double Day48BountyMult = 1.75d;
        internal const double Day48XpMult = 1.15d;
        internal const double Day49DropBonus = 0.3d;
        internal const double Day49XpMult = 1.2d;
        internal const double Day50NightmareMult = 2d;
        internal const double Day50DropBonus = 0.2d;
        internal const double Day51ShardMult = 1.5d;
        internal const double Day51BountyMult = 1.25d;
        internal const double Day52DropBonus = 0.15d;
        internal const double Day53XpMult = 1.25d;
        internal const double Day54NightmareMult = 1.5d;
        internal const double Day57ShardMult = 1.45d;
        internal const double Day57DropBonus = 0.1d;
        internal const double Day60XpMult = 1.3d;
        internal const double Day60ShardMult = 1.3d;
        internal static readonly string ContentFingerprintRecord = null;
    }
}
