// <auto-generated />
// Source: tools/balance/economy.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class EconomyBalance
    {
        internal const int DustPerBatch = 100;
        internal const int ShardsPerBatch = 10;
        internal const int MerchantBaseGold = 60;
        internal const int MerchantGoldPerHeat = 15;
        internal const int SalvageDustPerShard = 5;
        internal const int SalvageDustPerEnhance = 10;
        internal const double LimboDropBonus = 0.1;
        internal const double LimboLuck = 0.2;
        internal const int SecureBonusDivisor = 4;
        internal static readonly string ContentFingerprintRecord = null;
    }
}
