// Generated from tools/balance/equipment/caps.json. Do not edit.
namespace SodRpg.Core.Game
{
    internal static class EquipmentCapsBalance
    {
        internal const int Power_Momentum = 10;
        internal const int Power_Retaliation = 60;
        internal const int Power_Bulwark = 80;
        internal const int Power_Lifesteal = 20;
        internal const int Power_Thorns = 80;
        internal const int Power_Executioner = 120;
        internal const int Power_Resonance = 20;
        internal const int Power_Tailwind = 50;
        internal const int Power_Barrier = 25;
        internal const int Power_SecondWind = 60;
        internal const int Power_Blaze = 150;
        internal const int Power_ChainLightning = 120;
        internal const int Power_Shatter = 150;
        internal const int Power_Aegis = 40;
        internal const int Power_Bloodlust = 40;
        internal const int Power_Ember = 150;
        internal const int Power_Frost = 100;
        internal const int Power_Radiance = 200;
        internal const int Power_Umbra = 200;
        internal const int Power_Convergence = 300;
        internal const int Power_EchoingDodge = 150;
        internal const int Power_UltimateSurge = 50;
        internal const int Power_SoulSiphon = 40;
        internal const int Power_Whirlwind = 200;
        internal const int Power_Frenzy = 6;
        internal const int Power_OpeningStrike = 150;
        internal const int Power_StarShield = 40;
        internal const int Power_Sprint = 60;
        internal const int Power_Vigor = 40;
        internal const int Power_Overload = 50;
        internal const int Power_Finale = 50;
        internal const int Power_CriticalEcho = 12;
        internal const int Power_Fetters = 40;
        internal const int Power_CrystalResonance = 6;
        internal const int Power_PreyPride = 12;
        internal const int Power_OverflowingLife = 100;
        internal const int Power_Devotion = 10;
        internal const int Power_Wildfire = 60;
        internal const int Power_StillWater = 15;
        internal const int Power_SpendersWard = 20;
        internal const int Power_PerfectRead = 40;
        internal const int Power_LucidBoon = 18;
        internal const int Power_ShadowStep = 150;
        internal const int Power_Steam = 120;
        internal const int Power_Eclipse = 25;
        internal const int Power_Cinder = 1;
        internal const int Power_FrostCrystal = 12;
        internal const int Power_ShieldbreakBurst = 20;
        internal const int Power_SharedWard = 60;
        internal const int Power_ShieldBash = 90;
        internal const int Power_GleamingWard = 18;
        internal const int Power_CoStar = 30;
        internal const int Power_TriumphSong = 12;
        internal const int Power_WatchfulHand = 30;
        internal const int Power_KindnessReturns = 30;
        internal const int Power_WanderersEdge = 50;
        internal const int Power_FocusFire = 120;
        internal const int Power_Breakout = 18;
        internal const int Power_DuelistsWay = 60;
        internal const int Power_ImmovableStance = 20;
        internal const int Power_RunUp = 120;
        internal const int Power_StrafeShot = 40;
        internal const int Power_RelayHand = 15;
        internal const int Power_StardustCycle = 30;
        internal const int Power_UmbralHeritage = 100;
        internal const int Power_BrittleIce = 90;
        internal const int Power_ElementalHarvest = 60;
        internal const int Power_PrismShift = 5;
        internal const int Power_PackFeast = 8;
        internal const int Power_VanguardsOath = 45;
        internal const int Power_DeathBloom = 160;
        internal const int Power_Medley = 10;
        internal const int Power_Spellsweep = 90;
        internal const int Power_BareHandedPride = 3;
        internal const int Power_OpeningSalvo = 45;
        internal const int Power_PileOn = 60;
        internal const int Power_AceInHand = 24;
        internal const int Power_CrystalCircuit = 25;
        internal const int Power_ShardBoon = 15;
        internal const int Power_Lifeline = 12;
        internal const int Power_DreamOmen = 50;
        internal const int Power_RearguardsWay = 18;
        internal const int Power_TollOfGrudge = 40;
        internal const int Power_UnbowedMind = 12;
        internal const int Power_PilingLuck = 3;
        internal const int Power_WeakPointWound = 160;
        internal const int Power_CritSplash = 60;
        internal const int Power_ReturningBlade = 30;
        internal const int Power_ReadyGuard = 18;
        internal const int Power_Apothecary = 30;
        internal const int Power_SpilloverStrike = 120;
        internal const int Power_KillGoldPct = 12;
        internal const int Power_EliteKillGoldPct = 25;
        internal const int Power_DreamDustPct = 12;
        internal const int Power_DreamDustDelvePct = 10;
        internal const int Stat_AttackPct = 100;
        internal const int Stat_PowerPct = 100;
        internal const int Stat_AttackFlat = 250;
        internal const int Stat_PowerFlat = 250;
        internal const int Stat_AttackSpeedPct = 80;
        internal const int Stat_CritChancePct = 50;
        internal const int Stat_CritDamagePct = 150;
        internal const int Stat_MaxHealthPct = 120;
        internal const int Stat_MaxHealthFlat = 600;
        internal const int Stat_Armor = 150;
        internal const int Stat_HealthRegen = 40;
        internal const int Stat_Haste = 100;
        internal const int Stat_MoveSpeedPct = 35;
        internal const int Stat_Tenacity = 60;
        internal const int Stat_FireAmp = 100;
        internal const int Stat_ColdAmp = 100;
        internal const int Stat_LightAmp = 100;
        internal const int Stat_DarkAmp = 100;
        internal const int Stat_AttackRangePct = 30;
        internal const int Stat_FourthAttackShift = 1;
        internal const int Stat_EssenceSlotIdentity = 4;
        internal const int Stat_EssenceSlotMovement = 4;
        internal const int Stat_HealPower = 60;
        internal const int Stat_ShieldPower = 60;
        internal const int Stat_SummonPower = 80;
        internal const int Stat_SacrificeReduction = 40;

        internal static readonly string[] ContentFingerprintRecords = new string[]
        {
            "balance:equipment:caps:v1:power/AceInHand/cap:int32:value=24",
            "balance:equipment:caps:v1:power/Aegis/cap:int32:value=40",
            "balance:equipment:caps:v1:power/Apothecary/cap:int32:value=30",
            "balance:equipment:caps:v1:power/BareHandedPride/cap:int32:value=3",
            "balance:equipment:caps:v1:power/Barrier/cap:int32:value=25",
            "balance:equipment:caps:v1:power/Blaze/cap:int32:value=150",
            "balance:equipment:caps:v1:power/Bloodlust/cap:int32:value=40",
            "balance:equipment:caps:v1:power/Breakout/cap:int32:value=18",
            "balance:equipment:caps:v1:power/BrittleIce/cap:int32:value=90",
            "balance:equipment:caps:v1:power/Bulwark/cap:int32:value=80",
            "balance:equipment:caps:v1:power/ChainLightning/cap:int32:value=120",
            "balance:equipment:caps:v1:power/Cinder/cap:int32:value=1",
            "balance:equipment:caps:v1:power/CoStar/cap:int32:value=30",
            "balance:equipment:caps:v1:power/Convergence/cap:int32:value=300",
            "balance:equipment:caps:v1:power/CritSplash/cap:int32:value=60",
            "balance:equipment:caps:v1:power/CriticalEcho/cap:int32:value=12",
            "balance:equipment:caps:v1:power/CrystalCircuit/cap:int32:value=25",
            "balance:equipment:caps:v1:power/CrystalResonance/cap:int32:value=6",
            "balance:equipment:caps:v1:power/DeathBloom/cap:int32:value=160",
            "balance:equipment:caps:v1:power/Devotion/cap:int32:value=10",
            "balance:equipment:caps:v1:power/DreamDustDelvePct/cap:int32:value=10",
            "balance:equipment:caps:v1:power/DreamDustPct/cap:int32:value=12",
            "balance:equipment:caps:v1:power/DreamOmen/cap:int32:value=50",
            "balance:equipment:caps:v1:power/DuelistsWay/cap:int32:value=60",
            "balance:equipment:caps:v1:power/EchoingDodge/cap:int32:value=150",
            "balance:equipment:caps:v1:power/Eclipse/cap:int32:value=25",
            "balance:equipment:caps:v1:power/ElementalHarvest/cap:int32:value=60",
            "balance:equipment:caps:v1:power/EliteKillGoldPct/cap:int32:value=25",
            "balance:equipment:caps:v1:power/Ember/cap:int32:value=150",
            "balance:equipment:caps:v1:power/Executioner/cap:int32:value=120",
            "balance:equipment:caps:v1:power/Fetters/cap:int32:value=40",
            "balance:equipment:caps:v1:power/Finale/cap:int32:value=50",
            "balance:equipment:caps:v1:power/FocusFire/cap:int32:value=120",
            "balance:equipment:caps:v1:power/Frenzy/cap:int32:value=6",
            "balance:equipment:caps:v1:power/Frost/cap:int32:value=100",
            "balance:equipment:caps:v1:power/FrostCrystal/cap:int32:value=12",
            "balance:equipment:caps:v1:power/GleamingWard/cap:int32:value=18",
            "balance:equipment:caps:v1:power/ImmovableStance/cap:int32:value=20",
            "balance:equipment:caps:v1:power/KillGoldPct/cap:int32:value=12",
            "balance:equipment:caps:v1:power/KindnessReturns/cap:int32:value=30",
            "balance:equipment:caps:v1:power/Lifeline/cap:int32:value=12",
            "balance:equipment:caps:v1:power/Lifesteal/cap:int32:value=20",
            "balance:equipment:caps:v1:power/LucidBoon/cap:int32:value=18",
            "balance:equipment:caps:v1:power/Medley/cap:int32:value=10",
            "balance:equipment:caps:v1:power/Momentum/cap:int32:value=10",
            "balance:equipment:caps:v1:power/OpeningSalvo/cap:int32:value=45",
            "balance:equipment:caps:v1:power/OpeningStrike/cap:int32:value=150",
            "balance:equipment:caps:v1:power/OverflowingLife/cap:int32:value=100",
            "balance:equipment:caps:v1:power/Overload/cap:int32:value=50",
            "balance:equipment:caps:v1:power/PackFeast/cap:int32:value=8",
            "balance:equipment:caps:v1:power/PerfectRead/cap:int32:value=40",
            "balance:equipment:caps:v1:power/PileOn/cap:int32:value=60",
            "balance:equipment:caps:v1:power/PilingLuck/cap:int32:value=3",
            "balance:equipment:caps:v1:power/PreyPride/cap:int32:value=12",
            "balance:equipment:caps:v1:power/PrismShift/cap:int32:value=5",
            "balance:equipment:caps:v1:power/Radiance/cap:int32:value=200",
            "balance:equipment:caps:v1:power/ReadyGuard/cap:int32:value=18",
            "balance:equipment:caps:v1:power/RearguardsWay/cap:int32:value=18",
            "balance:equipment:caps:v1:power/RelayHand/cap:int32:value=15",
            "balance:equipment:caps:v1:power/Resonance/cap:int32:value=20",
            "balance:equipment:caps:v1:power/Retaliation/cap:int32:value=60",
            "balance:equipment:caps:v1:power/ReturningBlade/cap:int32:value=30",
            "balance:equipment:caps:v1:power/RunUp/cap:int32:value=120",
            "balance:equipment:caps:v1:power/SecondWind/cap:int32:value=60",
            "balance:equipment:caps:v1:power/ShadowStep/cap:int32:value=150",
            "balance:equipment:caps:v1:power/ShardBoon/cap:int32:value=15",
            "balance:equipment:caps:v1:power/SharedWard/cap:int32:value=60",
            "balance:equipment:caps:v1:power/Shatter/cap:int32:value=150",
            "balance:equipment:caps:v1:power/ShieldBash/cap:int32:value=90",
            "balance:equipment:caps:v1:power/ShieldbreakBurst/cap:int32:value=20",
            "balance:equipment:caps:v1:power/SoulSiphon/cap:int32:value=40",
            "balance:equipment:caps:v1:power/Spellsweep/cap:int32:value=90",
            "balance:equipment:caps:v1:power/SpendersWard/cap:int32:value=20",
            "balance:equipment:caps:v1:power/SpilloverStrike/cap:int32:value=120",
            "balance:equipment:caps:v1:power/Sprint/cap:int32:value=60",
            "balance:equipment:caps:v1:power/StarShield/cap:int32:value=40",
            "balance:equipment:caps:v1:power/StardustCycle/cap:int32:value=30",
            "balance:equipment:caps:v1:power/Steam/cap:int32:value=120",
            "balance:equipment:caps:v1:power/StillWater/cap:int32:value=15",
            "balance:equipment:caps:v1:power/StrafeShot/cap:int32:value=40",
            "balance:equipment:caps:v1:power/Tailwind/cap:int32:value=50",
            "balance:equipment:caps:v1:power/Thorns/cap:int32:value=80",
            "balance:equipment:caps:v1:power/TollOfGrudge/cap:int32:value=40",
            "balance:equipment:caps:v1:power/TriumphSong/cap:int32:value=12",
            "balance:equipment:caps:v1:power/UltimateSurge/cap:int32:value=50",
            "balance:equipment:caps:v1:power/Umbra/cap:int32:value=200",
            "balance:equipment:caps:v1:power/UmbralHeritage/cap:int32:value=100",
            "balance:equipment:caps:v1:power/UnbowedMind/cap:int32:value=12",
            "balance:equipment:caps:v1:power/VanguardsOath/cap:int32:value=45",
            "balance:equipment:caps:v1:power/Vigor/cap:int32:value=40",
            "balance:equipment:caps:v1:power/WanderersEdge/cap:int32:value=50",
            "balance:equipment:caps:v1:power/WatchfulHand/cap:int32:value=30",
            "balance:equipment:caps:v1:power/WeakPointWound/cap:int32:value=160",
            "balance:equipment:caps:v1:power/Whirlwind/cap:int32:value=200",
            "balance:equipment:caps:v1:power/Wildfire/cap:int32:value=60",
            "balance:equipment:caps:v1:stat/Armor/cap:int32:value=150",
            "balance:equipment:caps:v1:stat/AttackFlat/cap:int32:value=250",
            "balance:equipment:caps:v1:stat/AttackPct/cap:int32:value=100",
            "balance:equipment:caps:v1:stat/AttackRangePct/cap:int32:value=30",
            "balance:equipment:caps:v1:stat/AttackSpeedPct/cap:int32:value=80",
            "balance:equipment:caps:v1:stat/ColdAmp/cap:int32:value=100",
            "balance:equipment:caps:v1:stat/CritChancePct/cap:int32:value=50",
            "balance:equipment:caps:v1:stat/CritDamagePct/cap:int32:value=150",
            "balance:equipment:caps:v1:stat/DarkAmp/cap:int32:value=100",
            "balance:equipment:caps:v1:stat/EssenceSlotIdentity/cap:int32:value=4",
            "balance:equipment:caps:v1:stat/EssenceSlotMovement/cap:int32:value=4",
            "balance:equipment:caps:v1:stat/FireAmp/cap:int32:value=100",
            "balance:equipment:caps:v1:stat/FourthAttackShift/cap:int32:value=1",
            "balance:equipment:caps:v1:stat/Haste/cap:int32:value=100",
            "balance:equipment:caps:v1:stat/HealPower/cap:int32:value=60",
            "balance:equipment:caps:v1:stat/HealthRegen/cap:int32:value=40",
            "balance:equipment:caps:v1:stat/LightAmp/cap:int32:value=100",
            "balance:equipment:caps:v1:stat/MaxHealthFlat/cap:int32:value=600",
            "balance:equipment:caps:v1:stat/MaxHealthPct/cap:int32:value=120",
            "balance:equipment:caps:v1:stat/MoveSpeedPct/cap:int32:value=35",
            "balance:equipment:caps:v1:stat/PowerFlat/cap:int32:value=250",
            "balance:equipment:caps:v1:stat/PowerPct/cap:int32:value=100",
            "balance:equipment:caps:v1:stat/SacrificeReduction/cap:int32:value=40",
            "balance:equipment:caps:v1:stat/ShieldPower/cap:int32:value=60",
            "balance:equipment:caps:v1:stat/SummonPower/cap:int32:value=80",
            "balance:equipment:caps:v1:stat/Tenacity/cap:int32:value=60",
        };
    }
}
