// <auto-generated />
// Source: tools/balance/events.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class EventsBalance
    {
        internal const double OfferChance = 0.5;
        internal const double StargazerDropBonus = 0.3;
        internal const double LuckyStarLuck = 0.4;
        internal const int MerchantBaseShards = 50;
        internal const int MerchantShardsPerHeat = 10;
        internal const int TwinMirrorShards = 30;
        internal const int TwinMirrorEpicShards = 60;
        internal const double ChaliceWinChance = 0.5;
        internal const int ChaliceBonusMultiplier = 1;
        internal const int CauldronRelicCount = 3;
        internal const int TapirRelicsPerTuning = 3;
        internal const int CourageGateHeatIncrement = 1;
        internal const int CourageGateShards = 40;
        internal const int ArchiveBaseXp = 40;
        internal const int ArchiveXpPerHeat = 20;
        internal const int MemoryWellTuning = 1;
        internal const int MemoryWellEpicTuning = 2;
        internal const int ShadowExchangeShards = 25;
        internal const int ShadowExchangeEpicShards = 50;
        internal const int LostMausoleumShards = 60;
        internal const double RelicWagerRareWinChance = 0.2;
        internal const double RelicWagerLowerWinChance = 0.5;
        internal const int StoneBrokerShards = 35;
        internal const int StoneBrokerTuning = 2;
        internal const int ShardKilnTuning = 2;
        internal const int ShardKilnShards = 45;
        internal const int StarOfferingXp = 40;
        internal const int DreamOfferingBaseXp = 40;
        internal const int DreamOfferingXpPerHeat = 20;
        internal const int AbyssalChestShards = 75;
        internal const int AbyssalChestHeatIncrement = 1;
        internal const int SealedVaultShards = 40;
        internal const int OfferWeightsMerchant = 8;
        internal const int OfferWeightsFountain = 8;
        internal const int OfferWeightsChalice = 8;
        internal const int OfferWeightsLantern = 8;
        internal const int OfferWeightsForgeShrine = 8;
        internal const int OfferWeightsTwinMirror = 8;
        internal const int OfferWeightsStargazer = 8;
        internal const int OfferWeightsCauldron = 8;
        internal const int OfferWeightsTapir = 8;
        internal const int OfferWeightsCourageGate = 8;
        internal const int OfferWeightsArchive = 8;
        internal const int OfferWeightsLuckyStar = 8;
        internal const int OfferWeightsMemoryWell = 6;
        internal const int OfferWeightsShadowExchange = 8;
        internal const int OfferWeightsLostMausoleum = 5;
        internal const int OfferWeightsRelicWager = 6;
        internal const int OfferWeightsTemperingAltar = 6;
        internal const int OfferWeightsStoneBroker = 8;
        internal const int OfferWeightsShardKiln = 8;
        internal const int OfferWeightsStarOffering = 6;
        internal const int OfferWeightsDreamOffering = 6;
        internal const int OfferWeightsAbyssalChest = 5;
        internal const int OfferWeightsRelicExchange = 8;
        internal const int OfferWeightsSealedVault = 5;
        internal const int OfferWeightsPowerCrucible = 5;
        internal static readonly string ContentFingerprintRecord = null;
    }
}
