// <auto-generated />
// Source: tools/balance/forge.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class ForgeBalance
    {
        internal const int CurrentLevelOffset = 2;
        internal const int PercentPerLevel = 3;
        internal const int MaximumPercent = 45;
        // The original tuple contributes no record, preserving existing fingerprints.
        internal static readonly string ContentFingerprintRecord = null;
    }
}
