// <auto-generated />
// Source: tools/balance/infinity-bosses.json; regenerate with python tools/balance/gen_cs.py.
using System;
using System.Collections.Generic;

namespace SodRpg.Core.Game
{
    public static partial class InfinityBossSelection
    {
        public static IReadOnlyList<InfinityBossEntry> Entries { get; } = Array.AsReadOnly(new InfinityBossEntry[]
        {
            new InfinityBossEntry("Mon_Forest_BossDemon", "Zone_Forest", 10),
            new InfinityBossEntry("Mon_LavaLand_BossInfernus", "Zone_LavaLand", 10),
            new InfinityBossEntry("Mon_DarkCave_BossSeeker", "Zone_DarkCave", 10),
            new InfinityBossEntry("Mon_SnowMountain_BossSkoll", "Zone_SnowMountain", 10),
            new InfinityBossEntry("Mon_Sky_BossNyx", "Zone_Sky", 10),
            new InfinityBossEntry("Mon_Ink_BossWhiteNight", "Zone_Ink", 10),
            new InfinityBossEntry("Mon_Despair_BossAzurak", "Zone_Despair", 10),
            new InfinityBossEntry("Mon_Primus_BossPrimusAeron", "Zone_Primus", 10),
            new InfinityBossEntry("Mon_Special_BossErebos", null, 4),
            new InfinityBossEntry("Mon_Special_BossLightElemental", null, 4),
            new InfinityBossEntry("Mon_Special_BossObliviax", null, 4),
            new InfinityBossEntry("Mon_Special_BossMaw", null, 3),
            new InfinityBossEntry("Mon_Special_BossPolaris", null, 2),
        });
    }
}
