// <auto-generated />
// Source: tools/balance/infinity.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class InfinityBalance
    {
        internal const double ReferenceSeconds = 2100;
        internal const double RelicsPerHour = 24;
        internal const double GuaranteesPerHour = 0.25;
        internal const double ShardsPerHour = 180;
        internal const double TuningPerHour = 6;
        internal const double XpPerHour = 1200;
        internal const double StarXpPerHour = 780;
        internal const double AwakeningPerHour = 780;
        internal const double DustConversionsPerHour = 6;
        internal const double MerchantsPerHour = 6;
        internal const int KillMixLesser = 200;
        internal const int KillMixNormal = 160;
        internal const int KillMixMiniBoss = 5;
        internal const int KillMixBoss = 4;
        internal const double LesserTimeBurst = 10;
        internal const double NormalTimeBurst = 8;
        internal const double MiniBossTimeBurst = 1;
        internal const double BossTimeBurst = 1;
        internal const double HighRareBurst = 7;
        internal const double RelicsBurst = 24;
        internal const double LegendaryBurst = 7;
        internal const double GuaranteeOpportunitiesBurst = 1;
        internal const double GuaranteedRelicsBurst = 2;
        internal const double ShardsBurst = 30;
        internal const double TuningBurst = 3;
        internal const double XpBurst = 50;
        internal const double StarXpBurst = 20;
        internal const double AwakeningBurst = 20;
        internal const double DustConversionsBurst = 1;
        internal const double MerchantsBurst = 1;
        internal const double LesserRoomCap = 10;
        internal const double LesserRoomIncrement = 5;
        internal const double NormalRoomCap = 8;
        internal const double NormalRoomIncrement = 4;
        internal const double MiniBossRoomCap = 1;
        internal const double MiniBossRoomIncrement = 0.125;
        internal const double BossRoomCap = 1;
        internal const double BossRoomIncrement = 0.1;
        internal const int DefaultInterval = 10;
        internal const int ShortInterval = 10;
        internal const int MiddleInterval = 15;
        internal const int LongInterval = 20;
        internal const int MaximumPressureStage = 100;
        internal static readonly string ContentFingerprintRecord = null;
    }
}
