// <auto-generated />
// Source: tools/balance/infinity.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class InfinityBalance
    {
        internal const double UniqueDropMultiplier = 0.5;
        internal const int DefaultInterval = 10;
        internal const int ShortInterval = 10;
        internal const int MiddleInterval = 15;
        internal const int LongInterval = 20;
        internal const int MaximumPressureStage = 100;
        internal const int ShortPressureOffset = 4;
        internal const double ShortEnemyCountBonus = 4;
        internal const double ShortRelicMultiplier = 2;
        internal const int MiddlePressureOffset = 2;
        internal const double MiddleEnemyCountBonus = 2;
        internal const double MiddleRelicMultiplier = 1.5;
        internal const int LongPressureOffset = 0;
        internal const double LongEnemyCountBonus = 0;
        internal const double LongRelicMultiplier = 1;
        internal static readonly string ContentFingerprintRecord = "balance:infinity:v1:uniqueDropMultiplier:double:multiplier:0.5;intervalScaling/short/pressureOffset:int:stages:4;intervalScaling/short/enemyCountBonus:double:multiplier:4;intervalScaling/short/relicMultiplier:double:multiplier:2;intervalScaling/middle/pressureOffset:int:stages:2;intervalScaling/middle/enemyCountBonus:double:multiplier:2;intervalScaling/middle/relicMultiplier:double:multiplier:1.5";
    }
}
