// <auto-generated />
// Source: tools/balance/loot.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class LootBalance
    {
        internal static readonly int[] RarityWeights = { 3000, 1350, 500, 30, 2 };
        internal const double LesserDropChance = 0.008;
        internal const double NormalDropChance = 0.027;
        internal const double MiniBossDropChance = 0.45;
        internal const double BossDropChance = 1.0;
        internal const double MiniBossLuck = 0.6;
        internal const double BossLuck = 1.2;
        internal const double HeatDropBonus = 0.35;
        internal const double HeatLuck = 0.3;
        internal const double RarityLuckCoefficient = 0.6;
        internal const double BossExtraRelicChance = 0.6;
        internal const int FocusWeight = 2;
        internal const int SetPieceWeight = 4;
        internal const int SetCompletionWeight = 60;
        internal const double LesserShardChance = 0.05;
        internal const int LesserShards = 1;
        internal const double NormalShardChance = 0.12;
        internal const int NormalShardMin = 1;
        internal const int NormalShardMax = 2;
        internal const int MiniBossShardMin = 5;
        internal const int MiniBossShardMax = 10;
        internal const double MiniBossTuningChance = 0.2;
        internal const int MiniBossTuning = 1;
        internal const int BossShardMin = 20;
        internal const int BossShardMax = 30;
        internal const int BossTuning = 1;
        internal const int VariantAdditiveShards = 10;
        internal static readonly string ContentFingerprintRecord = null;
    }
}
