// <auto-generated />
// Source: tools/balance/pressure.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class PressureBalance
    {
        internal const int FreeDreamLevels = 5;
        internal const double HealthPerLevel = 0.06d;
        internal const double HealthPerStarPoint = 0.028d;
        internal const double HealthPerInfinityStage = 0.1d;
        internal const double DamagePerLevel = 0.016d;
        internal const double DamagePerStarPoint = 0.004d;
        internal const double DamagePerInfinityStage = 0.04d;
        internal const double EnemyCountHealthPerStage = 0.25d;
        internal const double EnemyCountPerStage = 0.08d;
        internal const double EnemyCountMaximumBonus = 4d;
        internal const double EnemyCountAdditionalRewardBudget = 0.5d;
        internal const double ShardDropPerPressure = 0.15d;
        internal const double ShardDropMaximum = 3d;
        internal const double NightmareChancePerPressure = 0.12d;
        internal const double NightmareChanceMaximum = 2.5d;
        internal const int MaximumDepth = 5;
        internal const double HealthPerDepth = 0.15d;
        internal const double DamagePerDepth = 0.08d;
        internal const double RarityLuckPerDepth = 0.25d;
        internal const double AwakeningPerDepth = 0.25d;
        internal const double StarXpPerDepth = 0.2d;
        internal const int ExtraNodesPerDepth = 2;
        internal static readonly string ContentFingerprintRecord = "balance:pressure:v1:dreamPressure/healthPerLevel:double:ratio/level:0.06;dreamPressure/healthPerStarPoint:double:ratio/point:0.028;dreamPressure/damagePerLevel:double:ratio/level:0.016;dreamPressure/damagePerStarPoint:double:ratio/point:0.004;dreamPressure/enemyCountHealthPerStage:double:health-ratio/stage:0.25;dreamPressure/enemyCountPerStage:double:ratio/stage:0.08;dreamPressure/enemyCountMaximumBonus:double:ratio:4;dreamPressure/enemyCountAdditionalRewardBudget:double:ratio:0.5;dreamPressure/shardDropPerPressure:double:multiplier/hp-bonus:0.15;dreamPressure/shardDropMaximum:double:multiplier:3;dreamPressure/nightmareChancePerPressure:double:multiplier/hp-bonus:0.12;dreamPressure/nightmareChanceMaximum:double:multiplier:2.5";
    }
}
