// <auto-generated />
// Source: tools/balance/star-progression.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class StarProgressionBalance
    {
        internal const int MaxPoints = 500;
        internal const int PointCostPerPoint = 6;
        internal const int PointCostOffset = 50;
        internal const int SecureXp = 20;
        internal const int VictoryXp = 100;
        internal const int NormalKillXp = 1;
        internal const int MiniBossKillXp = 5;
        internal const int BossKillXp = 20;
        internal const int NightmareMultiplier = 2;
        internal const int MaxKeystoneSlots = 3;
        internal static readonly int[] KeystoneUnlockLevels = { 200, 400 };
        internal static readonly string ContentFingerprintRecord = null;
    }
}
