// <auto-generated />
// Source: tools/balance/waypoints.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{
    internal static class WaypointBalance
    {
        internal const int Offered = 3;
        internal const double WeaponRoadLuck = 1d;
        internal const double ArmorRoadLuck = 1d;
        internal const double CharmRoadLuck = 1d;
        internal const double HeadRoadLuck = 1d;
        internal const double HandsRoadLuck = 1d;
        internal const double FeetRoadLuck = 1d;
        internal const double NightmareHuntNightmareChanceMultiplier = 2d;
        internal const double NightmareHuntNightmareRewardMultiplier = 2d;
        internal const double GlassAegisHealingMultiplier = 0.5d;
        internal const double GlassAegisShieldMultiplier = 2d;
        internal const double ResonantRoadReactionMultiplier = 2d;
        internal const double EndlessNightAwakeningMultiplier = 3d;
        internal const int TemperedFindsEnhancement = 2;
        internal const int TemperedFindsMaxRelicsPerRoom = 1;
        internal const double FleetingMemoriesMemoryCooldownMultiplier = 0.8d;
        internal const double FleetingMemoriesPressureMultiplier = 1.25d;
        internal const double SummonerTrailSummonPowerMultiplier = 1.5d;
        internal const double SummonerTrailHeroHealthMultiplier = 0.85d;
        internal const double EpicMirageShardMultiplier = 0d;
        internal const int ShardRoadRelicSalvageMultiplier = 3;
        internal const double TwinCacheTuningMultiplier = 0d;
        internal const int HumbleForgeEnhancement = 4;
        internal const double SixfoldRoadLuck = 0.5d;
        internal const int AwakeningPilgrimageAwakeningPerRelic = 20;
        internal const int FirstClaimMaxRelicsPerRoom = 1;
        internal const int TwinRelicCopies = 2;
        internal const int BossSalvageMultiplier = 4;
        internal const int StarXpPerShard = 4;
        internal const int HoardRewardMultiplier = 3;
        internal const int TuningPerNonBossRelic = 1;
        internal static readonly string ContentFingerprintRecord = null;
    }
}
