"""Stage typed boss-set drop constants; the existing boss-drop fingerprint owns them."""
from pathlib import Path

from star_values import read_json

ROOT = Path(__file__).resolve().parents[2]
PATH = ROOT / "tools/balance/boss-sets.json"
OUTPUT = ROOT / "src/SodRpg.Core/Game/Balance/BossSets.Generated.cs"
INT_MAX = (1 << 31) - 1
# Frozen schema/migration reference, not a runtime fallback.
LEGACY = {"schemaVersion": 1, "normalDropPercent": 10, "nightmareBonusPercent": 5,
          "depthBonusPercent": 1, "maxDropDepth": 5, "maxDropPercent": 20}
FIELDS = {"normalDropPercent": "NormalDropPercent", "nightmareBonusPercent": "NightmareBonusPercent",
          "depthBonusPercent": "DepthBonusPercent", "maxDropDepth": "MaxDropDepth", "maxDropPercent": "MaxDropPercent"}


def validate(data):
    if type(data) is not dict or set(data) != set(LEGACY):
        raise ValueError("boss-sets: expected exactly " + ", ".join(LEGACY))
    for key, value in data.items():
        if type(value) is not int or not 0 <= value <= INT_MAX:
            raise ValueError(f"boss-sets.{key}: expected nonnegative Int32, not boolean")
    if data["schemaVersion"] != 1:
        raise ValueError("boss-sets.schemaVersion: expected integer 1")
    for key in ("normalDropPercent", "nightmareBonusPercent", "depthBonusPercent", "maxDropPercent"):
        if data[key] > 100:
            raise ValueError(f"boss-sets.{key}: expected percent in 0..100")
    if data["normalDropPercent"] + data["nightmareBonusPercent"] + data["depthBonusPercent"] * data["maxDropDepth"] > INT_MAX:
        raise ValueError("boss-sets: uncapped chance arithmetic exceeds Int32")
    return data


def load(path=PATH):
    return validate(read_json(path))


def render_outputs(data=None):
    data = load() if data is None else validate(data)
    lines = ["// <auto-generated />", "// Source: tools/balance/boss-sets.json; regenerate with python tools/balance/gen_cs.py.",
             "namespace SodRpg.Core.Game", "{", "    internal static class BossSetsBalance", "    {"]
    for key, name in FIELDS.items():
        lines.append(f"        internal const int {name} = {data[key]};")
    lines += ["        // Existing ContentFingerprint boss-drop record includes all five adopted values.",
              "        internal static readonly string ContentFingerprintRecord = null;", "    }", "}", ""]
    return {OUTPUT: "\n".join(lines)}
