"""Compile exchange, merchant and salvage tuning without publishing files."""
import json
from decimal import Decimal
import math
from pathlib import Path

from star_values import read_json

ROOT = Path(__file__).resolve().parents[2]
PATH = ROOT / "tools/balance/economy.json"
OUTPUT = ROOT / "src/SodRpg.Core/Game/Balance/Economy.Generated.cs"
INT_MAX = (1 << 31) - 1
# Frozen compatibility reference, never a fallback balance source.
LEGACY = {"schemaVersion": 1, "exchange": {"dustPerBatch": 100, "shardsPerBatch": 10},
          "merchant": {"baseGold": 60, "goldPerHeat": 15},
          "salvage": {"dustPerShard": 5, "dustPerEnhance": 10},
          "expedition": {"limboDropBonus": Decimal("0.10"), "limboLuck": Decimal("0.2"), "secureBonusDivisor": 4}}
FIELDS = {
    "exchange.dustPerBatch": ("DustPerBatch", "dust/batch"),
    "exchange.shardsPerBatch": ("ShardsPerBatch", "shards/batch"),
    "merchant.baseGold": ("MerchantBaseGold", "gold"),
    "merchant.goldPerHeat": ("MerchantGoldPerHeat", "gold/heat"),
    "salvage.dustPerShard": ("SalvageDustPerShard", "dust/shard"),
    "salvage.dustPerEnhance": ("SalvageDustPerEnhance", "dust/enhance"),
    "expedition.limboDropBonus": ("LimboDropBonus", "drop-rate/limbo-depth"),
    "expedition.limboLuck": ("LimboLuck", "luck/limbo-depth"),
    "expedition.secureBonusDivisor": ("SecureBonusDivisor", "divisor"),
}


def _get(data, path):
    for key in path.split("."):
        data = data[key]
    return data


def _shape(data, reference, path="economy"):
    if isinstance(reference, dict):
        if type(data) is not dict or set(data) != set(reference):
            raise ValueError(f"{path}: expected exactly {', '.join(reference)}")
        for key in reference:
            _shape(data[key], reference[key], f"{path}.{key}")
    elif isinstance(reference, Decimal):
        if type(data) not in (int, Decimal) or not Decimal(data).is_finite() or data < 0:
            raise ValueError(f"{path}: expected finite nonnegative double")
        value = float(data)
        if not math.isfinite(value) or Decimal(repr(value)) != Decimal(data):
            raise ValueError(f"{path}: value must round-trip through double")
    elif type(data) is not int or not 0 <= data <= INT_MAX:
        raise ValueError(f"{path}: expected nonnegative Int32, not boolean")


def validate(data):
    _shape(data, LEGACY)
    if data["schemaVersion"] != 1:
        raise ValueError("economy.schemaVersion: expected integer 1")
    if data["expedition"]["secureBonusDivisor"] < 1:
        raise ValueError("economy.expedition.secureBonusDivisor: expected positive divisor")
    exchange = data["exchange"]
    if any(value < 1 or value * 10 > INT_MAX for value in exchange.values()):
        raise ValueError("economy.exchange: positive rates with ten-batch total fitting Int32 required")
    merchant = data["merchant"]
    if merchant["baseGold"] < 1 or merchant["baseGold"] + merchant["goldPerHeat"] * 5 > INT_MAX:
        raise ValueError("economy.merchant: positive price fitting Int32 through heat five required")
    # Use the adopted forge inputs; safety ceilings themselves remain fixed in Core.
    import forge_values
    forge = forge_values.load()
    maximum = max(shards * data["salvage"]["dustPerShard"]
                  + (forge["enhancement"]["baseCap"] + forge["enhancement"]["stepPerBreak"] * breaks) * data["salvage"]["dustPerEnhance"]
                  for shards, breaks in zip(forge["salvage"]["shards"], forge["limitBreak"]["maxByRarity"]))
    if maximum > 2000:
        raise ValueError("economy.salvage: adopted maximum exceeds fixed MaxDustEarnPerTrade safety ceiling 2000")
    return data


def load(path=PATH):
    return validate(read_json(path))


def _literal(value, reference):
    return repr(float(value)) if isinstance(reference, Decimal) else str(value)


def fingerprint_record(data):
    validate(data)
    records = [f"{path.replace('.', '/')}:{'double' if isinstance(_get(LEGACY, path), Decimal) else 'int'}:{unit}:{_literal(_get(data, path), _get(LEGACY, path))}"
               for path, (_, unit) in FIELDS.items()
               if _literal(_get(data, path), _get(LEGACY, path)) != _literal(_get(LEGACY, path), _get(LEGACY, path))]
    return "balance:economy:v1:" + ";".join(records) if records else None


def render_outputs(data=None):
    data = load() if data is None else validate(data)
    lines = ["// <auto-generated />", "// Source: tools/balance/economy.json; regenerate with python tools/balance/gen_cs.py.",
             "namespace SodRpg.Core.Game", "{", "    internal static class EconomyBalance", "    {"]
    for path, (name, _) in FIELDS.items():
        reference = _get(LEGACY, path)
        kind = "double" if isinstance(reference, Decimal) else "int"
        lines.append(f"        internal const {kind} {name} = {_literal(_get(data, path), reference)};")
    record = fingerprint_record(data)
    lines.append("        internal static readonly string ContentFingerprintRecord = " + (json.dumps(record) if record else "null") + ";")
    lines += ["    }", "}", ""]
    return {OUTPUT: "\n".join(lines)}
