"""Validate equipment coefficients and render without publishing files."""

import json
from pathlib import Path

from star_values import read_json

ROOT = Path(__file__).resolve().parents[2]
TABLE_PATH = ROOT / "tools/balance/gear.json"
OUTPUT_PATH = ROOT / "src/SodRpg.Core/Game/GearBalance.Generated.cs"
FIELDS = ("MaxItemLevel", "ItemLevelScalingCap", "BaseLevelScalePct",
          "FlatDamageGrowthPct", "OtherFixedGrowthPct")


def load_gear(path=TABLE_PATH):
    return validate_gear(read_json(path), path)


def validate_gear(table, path=TABLE_PATH):
    if not isinstance(table, dict) or set(table) != {"schemaVersion", *FIELDS}:
        raise ValueError(f"{path}: expected schemaVersion and exactly {', '.join(FIELDS)}")
    if type(table["schemaVersion"]) is not int or table["schemaVersion"] != 1:
        raise ValueError(f"{path}/schemaVersion: expected integer 1")
    for field in FIELDS:
        value = table[field]
        minimum = 0 if field.endswith("GrowthPct") else 1
        if type(value) is not int or not minimum <= value <= 2147483647:
            raise ValueError(f"{path}/{field}: expected Int32 integer >= {minimum}")
    if table["ItemLevelScalingCap"] > table["MaxItemLevel"]:
        raise ValueError(f"{path}: scaling cap exceeds maximum item level")
    maximum = table["BaseLevelScalePct"] + max(table["FlatDamageGrowthPct"], table["OtherFixedGrowthPct"]) * (table["ItemLevelScalingCap"] - 1)
    if maximum > 2147483647 // 130:
        raise ValueError(f"{path}: level scaling exceeds safe rarity multiplication range")
    return table


def render_outputs(table=None):
    table = load_gear() if table is None else validate_gear(table)
    # Historical stage-3 fingerprint fields only; caps are now authored in equipment/caps.json.
    legacy_record_table = {**table, "AttackFlatCap": 250, "PowerFlatCap": 250}
    record = "balance:gear:v1:" + json.dumps(legacy_record_table, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    lines = ["// <auto-generated />", "// Source: tools/balance/gear.json", "namespace SodRpg.Core.Game", "{", "    public static class GearBalance", "    {"]
    lines.extend(f"        public const int {field} = {table[field]};" for field in FIELDS)
    lines.append("        public const string ContentFingerprintRecord = " + json.dumps(record) + ";")
    lines.extend(["    }", "}", ""])
    return {OUTPUT_PATH: "\n".join(lines)}
