#!/usr/bin/env python3
"""Generate compile-time forge and star content; --check never writes files."""

import argparse
import importlib.util
import json
import sys
from pathlib import Path

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[2]
FORGE_PATH = ROOT / "tools" / "balance" / "forge.json"
OUTPUT_PATH = ROOT / "src" / "SodRpg.Core" / "Game" / "Balance" / "Forge.Generated.cs"
INT_MAX = (1 << 31) - 1
MAX_LEGAL_ENHANCE = 20
# Frozen compatibility tuple, not defaults for missing input.
LEGACY_COEFFICIENTS = (2, 3, 45)


def _unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate key: {key}")
        result[key] = value
    return result


def _validate(data):
    if type(data) is not dict or set(data) != {"schemaVersion", "enhanceFailure"}:
        raise ValueError("forge must contain exactly schemaVersion and enhanceFailure")
    if type(data["schemaVersion"]) is not int or data["schemaVersion"] != 1:
        raise ValueError("schemaVersion must be integer 1")
    failure = data["enhanceFailure"]
    fields = {"currentLevelOffset", "percentPerLevel", "maximumPercent"}
    if type(failure) is not dict or set(failure) != fields:
        raise ValueError("enhanceFailure must contain exactly the three forge coefficients")
    for name in fields:
        if type(failure[name]) is not int:
            raise ValueError(f"{name} must be an integer (not a boolean)")
    offset = failure["currentLevelOffset"]
    slope = failure["percentPerLevel"]
    cap = failure["maximumPercent"]
    if not 0 <= offset <= MAX_LEGAL_ENHANCE:
        raise ValueError(f"currentLevelOffset must be in 0..{MAX_LEGAL_ENHANCE}")
    if not 0 <= slope <= INT_MAX:
        raise ValueError("percentPerLevel must be a nonnegative Int32")
    if not 0 <= cap <= 100:
        raise ValueError("maximumPercent must be in 0..100")
    # Both endpoints matter: Math.Max executes after the signed multiplication.
    if max(offset, MAX_LEGAL_ENHANCE - offset) * slope > INT_MAX:
        raise ValueError("percentPerLevel product must fit Int32 at every legal enhancement level")
    return offset, slope, cap


def load_forge(path=FORGE_PATH):
    data = json.loads(Path(path).read_text(encoding="utf-8"), object_pairs_hook=_unique_object)
    _validate(data)
    return data


def render_forge(data):
    offset, slope, cap = _validate(data)
    record = "null" if (offset, slope, cap) == LEGACY_COEFFICIENTS else f'"balance:forge:v1:{offset}:{slope}:{cap}"'
    return f"""// <auto-generated />
// Source: tools/balance/forge.json; regenerate with python tools/balance/gen_cs.py.
namespace SodRpg.Core.Game
{{
    internal static class ForgeBalance
    {{
        internal const int CurrentLevelOffset = {offset};
        internal const int PercentPerLevel = {slope};
        internal const int MaximumPercent = {cap};
        // The original tuple contributes no record, preserving existing fingerprints.
        internal static readonly string ContentFingerprintRecord = {record};
    }}
}}
"""


def _star_generator():
    directory = ROOT / "tools" / "star-manifest"
    sys.path.insert(0, str(directory))
    spec = importlib.util.spec_from_file_location("balance_star_generator", directory / "gen_cs.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def generate(check=False):
    # Resolve and render every domain before publishing any file. Invalid new
    # star content cannot update forge while leaving an older star map behind.
    forge = render_forge(load_forge())
    stars = _star_generator()
    outputs = stars.render_outputs()
    outputs[OUTPUT_PATH] = forge
    return stars.publish_outputs(outputs, check=check)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated source is stale, without writing")
    args = parser.parse_args()
    try:
        return 0 if generate(check=args.check) else 1
    except (OSError, ValueError) as error:
        print(f"balance generation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
