"""Compile the independent Infinity boss lottery; no resource fingerprint changes."""
import json
import sys
from pathlib import Path
from star_values import read_json

ROOT = Path(__file__).resolve().parents[2]
PATH = ROOT / "tools/balance/infinity-bosses.json"
OUTPUT = ROOT / "src/SodRpg.Core/Game/Balance/InfinityBosses.Generated.cs"
NATIVE_ZONES = {
    "Mon_Forest_BossDemon": "Zone_Forest",
    "Mon_LavaLand_BossInfernus": "Zone_LavaLand",
    "Mon_DarkCave_BossSeeker": "Zone_DarkCave",
    "Mon_SnowMountain_BossSkoll": "Zone_SnowMountain",
    "Mon_Sky_BossNyx": "Zone_Sky",
    "Mon_Ink_BossWhiteNight": "Zone_Ink",
    "Mon_Despair_BossAzurak": "Zone_Despair",
    "Mon_Primus_BossPrimusAeron": "Zone_Primus",
    "Mon_Special_BossErebos": None,
    "Mon_Special_BossLightElemental": None,
    "Mon_Special_BossObliviax": None,
    "Mon_Special_BossMaw": None,
    "Mon_Special_BossPolaris": None,
}


def validate(data):
    if not isinstance(data, dict) or set(data) != {"schemaVersion", "entries"}:
        raise ValueError("infinity-bosses: expected schemaVersion and entries")
    if type(data["schemaVersion"]) is not int or data["schemaVersion"] != 1:
        raise ValueError("infinity-bosses: unsupported schemaVersion")
    entries = data["entries"]
    if not isinstance(entries, list) or len(entries) != len(NATIVE_ZONES):
        raise ValueError("infinity-bosses: expected exactly 13 entries")
    seen = set()
    total = 0
    for entry in entries:
        if not isinstance(entry, dict) or set(entry) != {"bossTypeName", "zoneId", "weight"}:
            raise ValueError("infinity-bosses: malformed entry")
        name = entry["bossTypeName"]
        if not isinstance(name, str) or name not in NATIVE_ZONES or name in seen:
            raise ValueError("infinity-bosses: unknown or duplicate boss")
        if entry["zoneId"] != NATIVE_ZONES[name]:
            raise ValueError("infinity-bosses: incorrect native zone mapping")
        weight = entry["weight"]
        if type(weight) is not int or weight < 0 or weight > 2147483647:
            raise ValueError("infinity-bosses: weight must be a nonnegative Int32")
        total += weight
        if total > 2147483647:
            raise ValueError("infinity-bosses: total weight overflows Int32")
        seen.add(name)
    return data


def load(path=PATH):
    return validate(read_json(path))


def render_outputs(data=None):
    try:
        data = load() if data is None else validate(data)
    except (OSError, ValueError) as error:
        print(f"infinity-bosses: disabling weighted lottery; native uniform-zone fallback: {error}", file=sys.stderr)
        # Retain known encounter metadata so Continue can restore an already selected boss.
        data = {"entries": [{"bossTypeName": name, "zoneId": zone, "weight": 0}
                            for name, zone in NATIVE_ZONES.items()]}
    lines = ["// <auto-generated />",
             "// Source: tools/balance/infinity-bosses.json; regenerate with python tools/balance/gen_cs.py.",
             "using System;", "using System.Collections.Generic;", "",
             "namespace SodRpg.Core.Game", "{", "    public static partial class InfinityBossSelection", "    {",
             "        public static IReadOnlyList<InfinityBossEntry> Entries { get; } = Array.AsReadOnly(new InfinityBossEntry[]", "        {"]
    for entry in data["entries"]:
        zone = "null" if entry["zoneId"] is None else json.dumps(entry["zoneId"])
        lines.append(f'            new InfinityBossEntry({json.dumps(entry["bossTypeName"])}, {zone}, {entry["weight"]}),')
    return {OUTPUT: "\n".join(lines + ["        });", "    }", "}", ""])}
