"""Validate and render ordinary set definitions; never load balance JSON at runtime."""

import json
from pathlib import Path
import re
from equipment_common import load_json

ROOT = Path(__file__).resolve().parents[2]
TABLE_PATH = ROOT / "tools/balance/equipment/sets.json"
OUTPUT_PATH = ROOT / "src/SodRpg.Core/Game/SetBalanceValues.g.cs"


def load_sets(path=TABLE_PATH):
    try:
        table = load_json(path)
    except (ValueError, OSError) as error:
        raise ValueError(f"{path}: {error}") from error
    return validate_sets(table, path)


def validate_sets(table, path=TABLE_PATH):
    if not isinstance(table, dict) or set(table) != {"schemaVersion", "sets"}:
        raise ValueError(f"{path}: expected exactly schemaVersion and sets")
    if type(table["schemaVersion"]) is not int or table["schemaVersion"] != 1:
        raise ValueError(f"{path}/schemaVersion: expected integer 1")
    rows = table["sets"]
    if not isinstance(rows, list) or len(rows) != 48:
        raise ValueError(f"{path}/sets: expected all 48 ordinary sets")
    source = (ROOT / "src/SodRpg.Core/Game/Content.cs").read_text(encoding="utf-8")
    expected = set(re.findall(r'new UniqueDef\("set\.[^"]+",[^\n]+, "(set\.[^"]+)"\)', source))
    expected = {sid for sid in expected if not sid.startswith("set.boss_")}
    enum_source = (ROOT / "src/SodRpg.Core/Game/Ids.cs").read_text(encoding="utf-8")
    enums = {}
    for kind in ("Stat", "Power"):
        match = re.search(r'public enum ' + kind + r'\s*\{(.*?)\}', enum_source, re.S)
        if match is None:
            raise ValueError(f"cannot find {kind} enum")
        body = re.sub(r'//[^\n]*', '', match.group(1))
        enums[kind.lower()] = set(re.findall(r'\b(\w+)\s*(?:=\s*\d+)?\s*(?:,|$)', body.strip()))
    seen = set()
    for index, row in enumerate(rows):
        prefix = f"{path}/sets/{index}"
        if not isinstance(row, dict) or set(row) != {"id", "name", "twoPiece", "threePiece", "sixPiece"}:
            raise ValueError(f"{prefix}: expected id, name, twoPiece, threePiece, sixPiece")
        sid = row["id"]
        if not isinstance(sid, str) or sid not in expected or sid in seen:
            raise ValueError(f"{prefix}/id: unknown or duplicate ordinary set {sid!r}")
        seen.add(sid)
        name = row["name"]
        if not isinstance(name, dict) or set(name) != {"ja", "en"} or any(not isinstance(v, str) or not v for v in name.values()):
            raise ValueError(f"{prefix}/name: expected nonempty ja and en strings")
        for stage, kind in (("twoPiece", "stat"), ("threePiece", "power"), ("sixPiece", "power")):
            lines = row[stage]
            if not isinstance(lines, list) or not lines:
                raise ValueError(f"{prefix}/{stage}: expected nonempty effect array")
            effects = set()
            for line in lines:
                if not isinstance(line, dict) or set(line) != {kind, "value"}:
                    raise ValueError(f"{prefix}/{stage}: expected {kind} and value")
                effect = line[kind]
                if not isinstance(effect, str) or effect not in enums[kind] or effect in effects:
                    raise ValueError(f"{prefix}/{stage}: unknown or duplicate {kind} {effect!r}")
                effects.add(effect)
                if type(line["value"]) is not int or not 0 < line["value"] <= 2147483647:
                    raise ValueError(f"{prefix}/{stage}/{effect}: expected positive Int32 value")
    if seen != expected:
        raise ValueError(f"{path}: missing ordinary sets: {sorted(expected - seen)}")
    return table


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def render_outputs(table=None):
    table = load_sets() if table is None else validate_sets(table)
    record = "balance:sets:v1:" + json.dumps(table, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    lines = ["// Generated by tools/balance/run from tools/balance/equipment/sets.json. Do not edit.",
             "namespace SodRpg.Core.Game", "{", "    internal static class SetBalanceValues", "    {",
             "        internal const string ContentFingerprintRecord = " + quote(record) + ";",
             "", "        internal static SetDef[] CreateSets() => new[]", "        {"]
    for row in table["sets"]:
        lines.extend(["            new SetDef", "            {",
                      f'                Id = {quote(row["id"])}, Name = new Txt({quote(row["name"]["ja"])}, {quote(row["name"]["en"])}),'])
        for field, stage, kind in (("TwoPiece", "twoPiece", "Stat"), ("ThreePiece", "threePiece", "Power"), ("SixPiece", "sixPiece", "Power")):
            effects = ", ".join(f'new {kind}Line({kind}.{line[kind.lower()]}, {line["value"]})' for line in row[stage])
            lines.append(f"                {field} = new[] {{ {effects} }},")
        lines.append("            },")
    lines.extend(["        };", "    }", "}", ""])
    return {OUTPUT_PATH: "\n".join(lines)}
